### ISSUE TITLE
About AMI architecture chart 

### ISSUE THREAD

**Issue by jinchengxiaoge** [FNNDSC/ami#102]
Hello, NicolasRannou
I am not clear, DCM image display order flow, 2D drawing flow diagrams, 3D images rendering aflow chart. Can you share this? thank you very much. Waiting for your return.

**Comment by jinchengxiaoge** [comment]
Hello, NicolasRannou  
     I am not clear, DCM image display order flow, 2D drawing flow diagrams, 3D images rendering aflow chart. Can you share this? thank you very much. Waiting for your return.

**Comment by NicolasRannou** [comment]
Loading: 
<img src="https://docs.google.com/drawings/d/1g1fqjJKVJ3b7Fil2GzeK308WuZmukQ-VlpJMKw-jieQ/pub?w=1181&amp;h=708">

**Comment by NicolasRannou** [comment]
Visualization:
<img src="https://docs.google.com/drawings/d/1L09gmPEu5pVBTTe2xvF3dvG-llmC5dLXWI6_I7Soy04/pub?w=960&amp;h=720">

**Comment by NicolasRannou** [comment]
Basically there is no difference between 2D and 3D, which is very powerful.
It is just a different way to look at the same object: Orthographic vs Perspective projections.

**Comment by jinchengxiaoge** [comment]
Thank you very much.
