### ISSUE TITLE
Ask for guidence 

### ISSUE THREAD

**Issue by jinchengxiaoge** [FNNDSC/ami#103]
Hello,NicolasRannou 
       I'm sorry to bother you again, I really want to understand AMI, I  am confused about the ray-casting algorithm of this framework, as well as the design scheme. Do you have any relatively  detailed description  of this part or related documentation ? Can you give me  the reference you  quote about when you design  this frame? I would like it to be my guidence during my research. I hope through in-depth understanding of the relevant literature to help me solve the problems in my programing. Thank you very much. Looking forward to your reply.

**Comment by rwirz** [comment]
Hi @jinchengxiaoge ,

 This is only a drop in the ocean!

AMI is based on Three.js and if you want lo learn AMI you need to understand before Three.js. 
For example, the raycasting feature comes from Three.js 

You can see an example here:

https://threejs.org/examples/?q=ray#webgl_interactive_raycasting_points

and the documentation of raycasting here:

https://threejs.org/docs/index.html?q=ray#Reference/Core/Raycaster

AMI load the structures as meshes (three.js object). And the Volume/Images is a object called Stack that has different slices and each slice is a mesh. So, all are meshes in the scene. It sound easy but it is difficult and @NicolasRannou is doing a great job!

**Comment by NicolasRannou** [comment]
Yes @rwirz says the Raycasting is handled by Three,js.

If you are talking about `raycasting`, in the context of `volume rendering`, we follow the simple algorithm from https://en.wikipedia.org/wiki/Volume_ray_casting, without the shading yet.

Waiting for full WebGL2 support in Three.js to go back to volume rendering.

**Comment by NicolasRannou** [comment]
Please re-open if needed
