### ISSUE TITLE
Registration Matrix with a Volume

### ISSUE THREAD

**Issue by rwirz** [FNNDSC/ami#105]
Hi,

If we have a Volume and we want to apply a registration matrix, what is the best way to do it?

The solution that I (believe) found is that we need to multiply the registration matrix with the matrix ijk2LPS (stack model).

So, we need to modify model.stack.js to include something like this inside computeIJK2LPS():

this._ijk2LPS = this._registrationMatrix*this._ijk2LPS;

Am i correct?

Thanks

**Comment by NicolasRannou** [comment]
Yes as far as I ca tell now I think that should work - did you give it a shot?

I am wondering if a better long term solution wouldn't be to keep `_registrationMatrix` and `_ijk2LPS` separate and use both when needed.

**Comment by rwirz** [comment]
I tried and it is working. This is my example code:

computeIJK2LPS() {
    this._ijk2LPS = new THREE.Matrix4();
	let regMatrix = new THREE.Matrix4();
	regMatrix.set(
	-0.999545,-0.023569,0.018786,44.958416,
	0.022023,-0.996659,-0.078650,-2.742024,
	0.020577,-0.078200,0.996725,-179.169698,
	0.000000,0.000000,0.000000,1.000000);
    this._ijk2LPS.set(
      this._xCosine.x * this._spacing.x, this._yCosine.x * this._spacing.y, this._zCosine.x * this._spacing.z, this._origin.x,
      this._xCosine.y * this._spacing.x, this._yCosine.y * this._spacing.y, this._zCosine.y * this._spacing.z, this._origin.y,
      this._xCosine.z * this._spacing.x, this._yCosine.z * this._spacing.y, this._zCosine.z * this._spacing.z, this._origin.z,
      0, 0, 0, 1);
	 
    this._ijk2LPS.premultiply(regMatrix);
    this._lps2IJK = new THREE.Matrix4();
    this._lps2IJK.getInverse(this._ijk2LPS);
  }

I will do a fork and upload a generic solution if you dont mind.

**Comment by NicolasRannou** [comment]
Glad it worked! And yes please send a pull request! :)
