### ISSUE TITLE
[help] use with react, import issue

### ISSUE THREAD

**Issue by chenkaiC4** [FNNDSC/ami#108]
First of all, WELL WORK! 👍 👍 👍 

### Description
I want to use ami with React, and select [react-react-app](https://github.com/facebookincubator/create-react-app) as a starter.

but when require ami,

``` js
import AMI from 'ami.js'
```

I got `unexpected token import`, Becuase the file at `src/` is not `CommonJS style`. 

So, I just use babel to transform `src/` to `lib/`，and set `mian` value at `package.json` to `lib/ami.js`。

``` bash
 babel src -d lib
```

Now, the `import` operation is OK, but some code like:

``` js
import coreIntersections from '../../src/core/core.intersections'
```

cause invoke error. Because `../../src/core/core.intersections` is a absolute path, take the invoke logic to `src` path instead of `lib`.

### suggestion

1. transform the es6 code to CommonJS, example like [react-router](https://github.com/ReactTraining/react-router)
2. don't invoke modules with `../../src/core/*` style, it's just like absolute path.

**Comment by NicolasRannou** [comment]
Yes I se what you mean - getting rid of `src` in `../../src/core/core.intersections` would make it work for you, right?

actually having `src` when importing module doesn't make sense and should be removed.
`import coreIntersections from '../../src/core/core.intersections'` should be `'import coreIntersections from '../core/core.intersections'`.

I'd like to keep it all `es6` rather than common as it is a standard and there should always be a way for people to use the library if it follows standards properly.

What you you think?

**Comment by chenkaiC4** [comment]
@NicolasRannou Thanks for your reply.

yes, I agree with you to remove `/../src` at those files, and I am glad to send a PR for this.

About the es6 and commonjs, i think ami is a good frontend project writted by es6, just like [react-router](https://github.com/ReactTraining/react-router)( react-router as a frontend project also written by es6 )。

ok, the key problem why we have to change es6 to commonjs at frontend project is that we use `npm` invoke the package installed at node_modules, and use `babel` or with `webpack` to allow us written es6 code。But, the transform rule also not include `node_modules` path, so package written with es6 will crash the project for es6 code. we can see almost all package such like `react-router`, `react` will use babel to transform source code to es5。

**Comment by chenkaiC4** [comment]
@NicolasRannou,  i have used babel to transform es6 code to commonjs style code, and publish a `fake` npm package named [ami-cjs.js](https://www.npmjs.com/package/ami-cjs.js)。Now i can require ami successfully, I will send another PR for this, hope that you will recieve it, so i don't have  to keep track of this two repo, and focus on giving ami a well react wrapper.

**Comment by chenkaiC4** [comment]
@NicolasRannou I have send the transform code at the #110 , All code have test at local successfully. I am pleased to receive questions and discussions about it.

**Comment by NicolasRannou** [comment]
Looking good to me thanks!
