### ISSUE TITLE
npm script dist:prepare not work, maybe not have local env config

### ISSUE THREAD

**Issue by chenkaiC4** [FNNDSC/ami#109]
### Description

when run `npm run dist:prepare`, show error:

``` js
> ami.js@0.0.16-dev dist:prepare /Users/chenkai/visual/webgl/ami
> node ./scripts/$npm_package_config_mode.js --dist

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/chenkai/visual/webgl/ami/scripts/.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

It seems like that the env `$npm_package_config_mode` is not defined.

### Versions
- AMI: dev branch

**Comment by NicolasRannou** [comment]
Yes it expects `$npm_package_config_mode` to be defined.
I think in general the build/dev system should/could be improved (i.e. simplified), especially with the `cross-env` npm package that I was not aware of.

`npm run dist:prepare` is not meant to be run manually at this point...

Right now the workflow is:

Develop a lesson:
`npm run demo <lesson>`

Develop a lesson:
`npm run lesson <lessonid>`

The big difference is that `demo` runs against the compiled `ami.js` and `lesson` compiles the lesson itself. Also the JS files have different naming conventions between lessons and examples. 'lessons' requires the JS file to be called demo.js to load properly in JSFiddle. In both cases we want to auto-refresh the browser when something changed in the code.

**Comment by chenkaiC4** [comment]
@NicolasRannou Hi morning~（though here is almost 11 pm）

thanks for your detailed explanation, i am glad to do some work at improving the npm scripts, tomorrow i will send a PR for it.
