### ISSUE TITLE
improve source code with more api ducuments, tests

### ISSUE THREAD

**Issue by chenkaiC4** [FNNDSC/ami#112]
@NicolasRannou 

Hi, this is a awesome project at Medical Imaging. I'd like to add more api ducuments to source code, and pretty the source code with `eslint`. Also write more test case.

Today I have just done some work at module `loader`, see PR #111 .
Hope to get your support and advice! 😃

**Comment by NicolasRannou** [comment]
Yes that is awesome thanks a lot! Will have a look soon!

Talking about the loader, what do you think about this one: 
https://github.com/FNNDSC/ami/issues/87
The idea is that the loader should just fire progress events and not include the "progress helper". That will make things more decoupled, easier to test and cleaner in general.
The "progress helper" should just catch the events later on.

**Comment by chenkaiC4** [comment]
Yes, decoupe the progress bar and loader is better design. Let's discussion at #87 。

**Comment by NicolasRannou** [comment]
Closing in favor of #87
