### ISSUE TITLE
About Volume rendering

### ISSUE THREAD

**Issue by jinchengxiaoge** [FNNDSC/ami#113]
Hello,NicolasRannou
       I met a problem when i ues the ami.js, and i want to get the profesional guild from you. Here is the problem.
      The volume rendering shows the result like fig1 when i import a group of dicom image by using ami.js-0.0.10 version
![20170309153316](https://cloud.githubusercontent.com/assets/24455151/23740260/c4227240-04dd-11e7-9ebb-c5c6b03fe741.png)

      The volume rendering shows the result like fig2 when i import a group of dicom image by using ami.js-0.0.15 version
![20170309153445](https://cloud.githubusercontent.com/assets/24455151/23740304/f649b990-04dd-11e7-8093-131388a4c3a8.png)
      Could you tell me why would this happen?
      Moreover.i want to utilize the update version to get the result shown in fig1,and when the latest ami.js relesed ?
      Thank you very much. Looking forward to your reply.

**Comment by NicolasRannou** [comment]
Interesting. It still looks different if you put the same number of steps and alpha correction?

Can you share the data by any chance?

Thanks!

**Comment by jinchengxiaoge** [comment]
yes . When i put the same number of steps and alpha correction it still looks different.
![20170309164535](https://cloud.githubusercontent.com/assets/24455151/23742516/13f287f6-04e8-11e7-90e7-09b61f612e73.png)

link：http://pan.baidu.com/s/1dEPohRN                 Password   ：7y4g

**Comment by NicolasRannou** [comment]
Thanks

**Comment by NicolasRannou** [comment]
Without looking at the data yet, my guess it that maybe the data contains negative values that where not properly handled before... Will keep you posted

**Comment by NicolasRannou** [comment]
Also can you post screenshots with different transfer functions?
Do you have a live demo by any chance? JSFiddle?

**Comment by jinchengxiaoge** [comment]
sorry .  I don't have a live demo by any chance. You can import these images directly into your lesson-06 demo.

**Comment by NicolasRannou** [comment]
Are you using the Volume Rendering Helper?

If so, as a test, can you set the window center width uniforms to the following values:
```
volumeRenderingHelper._uniforms.uWindowCenterWidth.value =
    [this._stack.windowCenter, this._stack.windowWidth * 0.8];
```

If not using the Volume Rendering Helper, can you set the Volume Rendering material uniforms to:
```
var offset = this._stack._minMax[0];
uniforms.uWindowCenterWidth.value =
    [offset + this._stack.windowCenter, this._stack.windowWidth * 0.8];
```

"offset" was introduced to shift all the pixels value in order to only deal with > 0 values on the shader side.

**Comment by jinchengxiaoge** [comment]
Thank you very much, this has been resolved, you are the best.
