### ISSUE TITLE
Quadview

### ISSUE THREAD

**Issue by Humphrey8** [FNNDSC/ami#114]
Hi,NicolasRannou
         The library warning don't contain the HelpersLocalizer method when i reproduce the quadview by using the 0.0.15 version of ami.js library.
          Thank you . Looking forward to your reply.

**Comment by NicolasRannou** [comment]
Hi @Humphrey8  -

It is because the localizer is only available from `0.016-dev`. Did you try to get the #dev branch from Github?

Will try to cut a new release shortly!

Thanks
