### ISSUE TITLE
[feature] Shader should be able to unpack negative values.

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ami#116]
Right now, we need to have the "offset trick" to only pass positive values to the shader, which can be confusing.

https://github.com/FNNDSC/ami/blob/dev/src/helpers/helpers.volumerendering.js#L54-L57
and same for slice Helper.

**Comment by daron1337** [comment]
Hello,
I have a DICOM dataset with a negative min value (-11300) and its max is about 16000
I think that the offset value should be -1.0 * min value, otherwise we shift the window center in the opposite direction.

```
let offset = 0;
    if (this._stack._minMax[0] < 0) {
      offset -=  this._stack._minMax[0];
    }
```

**Comment by NicolasRannou** [comment]
Hi @daron1337 - did you experience some issue? If so can you share an anonymized dataset?

The offset is meant to make sure all values passed to the shaders are positive, as we currently do not have method to unpack negative values from the textures in the shaders.

In you case, your values are going from `-11300` to `16000`, therefore the offset is `11300`.
Before packing the values into the texture we then add the offset to the value:

```
Value -11300 become 0 (-11300 + offset)
Value 0 becomes 11300 (0 + offset)
Value 16000 becomes 17300 (16000 + offset)
and so on...
```

Does it make sense?

**Comment by daron1337** [comment]
Ok, I understand.
I was not able to visualize the data in VR (everything was gray). The only way to see something was to shift Window center and Window Width with the offset value.

This is the default situation:
<img width="496" alt="screen shot 2017-09-27 at 10 05 11" src="https://user-images.githubusercontent.com/572819/30902604-1545175e-a36c-11e7-8ef9-afb5a73bd53f.png">

This is with my workaround:

<img width="497" alt="screen shot 2017-09-27 at 10 06 05" src="https://user-images.githubusercontent.com/572819/30902624-30b327d8-a36c-11e7-991d-f1af89f31fee.png">

```
var offset = 0;
      if (this._stack._minMax[0] < 0) {
        offset -= this._stack._minMax[0];
      }

```

`this._uniforms.uWindowCenterWidth.value = [offset + this._stack.windowCenter, offset + this._stack.windowWidth * 0.8];`

This is the anonymized dataset:
https://data-orbx.s3.amazonaws.com/dataset.zip

**Comment by NicolasRannou** [comment]
yes! did you try the "Volume Rendering Helper" by any chance? 
https://github.com/FNNDSC/ami/blob/dev/src/helpers/helpers.volumerendering.js

**Comment by daron1337** [comment]
Yes, I'm using the vrHelper as illustrated in the volumeRendering example.

**Comment by daron1337** [comment]
@NicolasRannou did you try the dataset? Using the vrHelper as illustrated I was not able to visualize the data in VR (everything was gray). The only way to see something was to shift Window center and Window Width with the offset value * -1.0

**Comment by daron1337** [comment]
@NicolasRannou I think it's better to set window center and window width in the uniform of the VRHelper during its initialization. 
If the stack has its min value < 0, we shift the center of the window with the offset
Problem solved.

```
var offset = vrHelper._stack._minMax[0] < 0 ? -1.0 * vrHelper._stack._minMax[0] : 0;
var windowCenter = 0.5 * (minMax[0] + minMax[1]) + offset;
var windowWidth = 0.7 * (minMax[1] - minMax[0]);
vrHelper.uniforms.uWindowCenterWidth.value = [windowCenter, windowWidth];
```

**Comment by NicolasRannou** [comment]
I didn't try to load it yet - what I am surprised it that the code you described is what is currently supposed to be happening in the constructor:
```
this._uniforms.uWindowCenterWidth.value = [offset + this._stack.windowCenter, this._stack.windowWidth * 0.8];
```

What may be happening after though is that windowCenter/width may reset somehow?

I was gonna suggest to add getters/setters for windowCenter/Width in the VR Helper to hide it from the end user:
```
cont vrHelper = ...
// before
var offset = vrHelper._stack._minMax[0] < 0 ? -1.0 * vrHelper._stack._minMax[0] : 0;
var windowCenter = 0.5 * (vrHelper._stack._minMax[0] + vrHelper._stack._minMax[1]) + offset;
var windowWidth = 0.7 * (vrHelper._stack._minMax[1] - vrHelper._stack._minMax[0]);
vrHelper.uniforms.uWindowCenterWidth.value = [windowCenter, windowWidth];

// now
vrHelper.windowCenter = ... (can be positive or negative)
vrHelper.windowWidth = ...

and also in VRHelper
  in constructor:
  this._offset = this._stack._minMax[0] < 0 ? -1.0 * this._stack._minMax[0] : 0;
  this._windowCenter = 0.5 * (this._stack._minMax[0] + this._stack._minMax[1]) + offset;
  this._windowWidth = 0.7 * (this._stack._minMax[1] - this._stack._minMax[0]);
  this._uniforms.uWindowCenterWidth.value = [this._windowCenter, this._windowWidth];

  set windowCenter(windowCenter) {
    this._windowCenter = this._offset +windowCenter;
    this._uniforms.uWindowCenterWidth.value = [this._windowCenter, this._windowWidth];
  }

  set windowWidth(windowWidth) {
    this._windowWidth = windowWidth < 0 ? 0 : windowWidth;
    this._uniforms.uWindowCenterWidth.value = [this._windowCenter, this._windowWidth];
  }
```

Do you think that could work?

**Comment by daron1337** [comment]
Yes it's fine, I agree.

The problem is that there's a mismatch between minMax and stack.windowCenter and stack.windowWidth when you compensate with the offset.

`this._stack._minMax = [-12711, 16383]`
while
`stack.windowCenter = 1800`
`stack.windowWidth   = 6000`
 
But if you compensate for the offset to only pass > 0 values to shaders, you need to move also the windowWidth not only WindowCenter.

By the way offset has to be negated
```
if (this._stack._minMax[0] < 0) {
  offset = this._stack._minMax[0];  // offset has to a be positive value
}
```
thus:
```
if (this._stack._minMax[0] < 0) {
  offset -= this._stack._minMax[0];  // offset has to a be positive value
}
```

**Comment by NicolasRannou** [comment]
> The problem is that there's a mismatch between minMax and stack.windowCenter and stack.windowWidth when you compensate with the offset.

Yes those should always hold the real values. (no compensated)

> But if you compensate for the offset to only pass > 0 values to shaders, you need to move also the windowWidth not only WindowCenter.

Not sure to understand - the "width" should always be the same before and after compensation.

> By the way offset has to be negated

Yep

I'll try to fix that shortly - so the idea is to have the "user" always provide the real values and we just may need to require usage of setters/getters to make sure things are properly compensated.

Does it sound fine?

**Comment by daron1337** [comment]
Perfect, thanks.

**Comment by JSibir** [comment]
Offset bug is fixed [here](https://github.com/FNNDSC/ami/pull/269)
