### ISSUE TITLE
Volume rendering 

### ISSUE THREAD

**Issue by Humphrey8** [FNNDSC/ami#122]
Hello,NicolasRannou
       when i ray-cast  a series of dicoms ,with the increasing of steps and inerpolation, MS will show full bin, which lead to the  entire page caton. I wandor the reason and the solution of that.
      Thank you very much. Looking forward to your reply.

**Comment by NicolasRannou** [comment]
Hmmm what do you mean "show full bin" @Humphrey8 ?

Also, try to make you web browser smaller to reduce the VR computations as a test - I am waiting for the WebGL2 support in ThreeJS to refactor the Volume Rendering, I hope it will have a huge impact on performance.

**Comment by Humphrey8** [comment]
I mean this 
![qq 20170320192917](https://cloud.githubusercontent.com/assets/26323700/24098060/a66de094-0da3-11e7-851a-558a5d4c2053.png).
when i  increase the steps and inerpolation,  it will be full, and the entire page Caton

**Comment by NicolasRannou** [comment]
Yes it is because at this time, interpolation is pretty expensive GPU-wise and also the step there is the more slow it gets.

There are ways to optimize but really hope WebGL2 support will make it much much faster.

Please let me know if you are interested to look into it or want more details!
