### ISSUE TITLE
[help] viewers_quadview example data source problem

### ISSUE THREAD

**Issue by chenkaiC4** [FNNDSC/ami#123]
@NicolasRannou What a SUPER example !

i'm doing some work at viewers_quadview, this effect is exactly what I need.
but when i write my codes according to the example, i got unexpected view. i confused what's wrong. Eventually I realized the data i have used is **CT data**. and only **saggital** view is correct.

my data is below, i have replace the example data with my CT data.

``` js
  let files = [];
  for (let i = 1; i <= 24; i++) {
    files.push('http://omfn6wd3b.bkt.clouddn.com/IM' + i + '.dcm');
  }

  let loader = new LoadersVolume();
  loader.load(files).then......
```

seem like problem is at the `initHelpersLocalizer` function, but i don't know how to correct it.

![image](https://cloud.githubusercontent.com/assets/7543145/24290799/45fbf6f8-10c1-11e7-8a2d-b842ab1a9ad0.png)

### Versions
- AMI: build from current dev branch

**Comment by NicolasRannou** [comment]
Yes that looks messed up - weird - can you tell which data you are trying to look at? Just replacing the data as you did should at least display it properly.

**Comment by NicolasRannou** [comment]
Does it print any error in the console by the way?

**Comment by chenkaiC4** [comment]
no error, i have replace the data at the example data, the Screenshot is the result.

**Comment by NicolasRannou** [comment]
@chenkaiC4  hmm - can you share the data or load another dataset as a test?

can you visualize your data properly in https://fnndsc.github.io/ami/#viewers_upload?

**Comment by chenkaiC4** [comment]
@NicolasRannou i have test my data with the example code. my data is CT data, does it will cause this? the nii data is fine.

**Comment by chenkaiC4** [comment]
my data have give at above, the url is just fine. 24 files.

**Comment by chenkaiC4** [comment]
visualize my data correct in https://fnndsc.github.io/ami/#viewers_upload.

**Comment by NicolasRannou** [comment]
looking at it... @chenkaiC4

**Comment by chenkaiC4** [comment]
@NicolasRannou how i want to solve it, but i found that I lack the knowledge of webgl and three.js, today i have buy two book of webgl and three to improve myself. hope to understand your magic code which bring such magic effect !

**Comment by NicolasRannou** [comment]
yes don't worry not sure what is going on yet - seems something is going wrong in the localizer shader so it is a bit more complex to debug than regular JS

**Comment by chenkaiC4** [comment]
@NicolasRannou i found the second slice is right. I think it's a clue,  but i am learning the shader program...

**Comment by chenkaiC4** [comment]
@NicolasRannou something like  x , y, z   <--reverse-->  z, y, x. the y is right

**Comment by Humphrey8** [comment]
I replaced the data format with ct. The same problem. How to solve this problem? Thank you.



![qq 20170329113814](https://cloud.githubusercontent.com/assets/26323700/24437626/bc1b8f4a-1474-11e7-85c2-9be2eec1b418.png)

**Comment by chenkaiC4** [comment]
@NicolasRannou I am working hard to find the bug at shader of localizer, but i find that i don't have a clear view of the logic that make such magic effect.

i have read the book <webgl programming guide> 😃  and read the src of `localizer.xxx.js`.

however, i have some problems or questions need you helper. 

1. at `helpers.localizer.js`, i see following [code](https://github.com/FNNDSC/ami/blob/dev/src/helpers/helpers.localizer.js#L72):

``` js
this._material = new THREE.ShaderMaterial(
        {side: THREE.DoubleSide,
         uniforms: this._uniforms,
         vertexShader: vs.compute(),        // where is the vertex data, i just see `position` at the main func
         fragmentShader: fs.compute(),
        });
```

as raw webgl have to bind data to vertex shader, so where is the vertex data, i just see `position` at the main.

2. what the logic to create the cross line ? i see the `plane`, the three.js say it's a infinite 2d surface.

```js 
_this.localizerHelper = new HelpersLocalizer(volume, _this.stackHelper.slice.geometry, selfPlane);
    for (let i = 0; i < localizers.length; i++) {
      _this.localizerHelper['plane' + (i + 1)] = localizers[i].plane;
      _this.localizerHelper['color' + (i + 1)] = localizers[i].color;
    }
```
the example code use `stackHelper.slice.cartesianEquation()` to get the plane, yes, every slice can extend to be a plane (i got it 😄 ). when  `new HelpersLocalizer`, the plane will be used. Oh! the second args of Class `HelpersLocalizer`, is a geometry, is it the vertex data of question 1 above ? ok, continue question 2, at the `for loop`, set the other two slice's plane and color. i guess if we get the `coincidence line` of each plane based at current slice and draw the color, we will get the magic cross line effect, dose it?

3. from the bad result by the ct data, it seems like the `coincidence line` is loss or been set as the all slice, however this Hypothesis is based at `coincidence line` plan, i just can't confirm your logic of draw cross line by the code. and from the [code](https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.localizer.fragment.js#L161)

```js 
      vec3 colorMix = c1.xyz*c1.w + c2.xyz*c2.w + c3.xyz*c3.w;
      gl_FragColor = vec4(colorMix, max(max(c1.w, c2.w),c3.w));
```

i was confused that why the all slice will be coverd by the color of one of the two localizer?  the localizer shader seems do some work exceed his duty. howerver, this just appear when use **ct data** , confused! the data format will cause xxx? i hope give your some clue.

**Comment by NicolasRannou** [comment]
Hey @chenkaiC4 thanks for looking into it - I have been doing some investigation too and I think the problem is there: https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.localizer.fragment.js#L59-L82

The following line in particular:
```
      float x = (b1*d2 - b2*d1) / (a1*b2 - a2*b1);
      float y = (a2*d1 - a1*d2) / (a1*b2 - a2*b1);
```

When `a1*b2 - a2*b1` is equals to 0, `x` and `y` are not properly computed.

Will answer to your questions in details in a bit.

**Comment by chenkaiC4** [comment]
@NicolasRannou 😄  i just read this section, if 4 years ago, i think i could compute it out, but now i forget those all......

**Comment by NicolasRannou** [comment]
@chenkaiC4 @Humphrey8  the latest version of AMI should work, please let me know if something doesn't look right!

**Comment by chenkaiC4** [comment]
@NicolasRannou 🥂  wonderful work !!!
