### ISSUE TITLE
Image blending

### ISSUE THREAD

**Issue by FredChamp** [FNNDSC/ami#126]
Hi everybody,

I want to display segmentation mask as an overlay of my DICOM image.
I tried your lesson 04 viewers_labelmap but the modality SEG is not supported or implemented by most of the tools used to segment images...

So, is it possible to display a mask even if it's not a SEG modality?
Moreover, it would be nice if we can upload other formats for segmentation like mhd/raw, vtk, itk, etc...

**Comment by NicolasRannou** [comment]
Yes, you can overlay any kind of data as long as we can parse it (dcm, nii, mhd/raw, nrrd).

Did you have a look at this [one](https://fnndsc.github.io/ami/#viewers_compare)?

For models (vtk) see the approach used [there](https://fnndsc.github.io/ami/#viewers_quadview)

Does it help?

**Comment by FredChamp** [comment]
In the second example, in the 2D renderers, do the masks are sections representations of the 3D models?
Because the source you are only uploaded .stl and a DICOM.

Many thanks for you quick answers!

**Comment by NicolasRannou** [comment]
Yes @FredChamp, is is a representation of the intersection between the 3D model and the slice.

Example 1 was to highlight how to overlay 2 "images" and the second example was about images + 3D models.

**Comment by FredChamp** [comment]
Thank you Nicolas!

Just a last question: do you have any example of how to overlay a mhd/raw image over a DICOM?

**Comment by NicolasRannou** [comment]
@FredChamp not yet but if you have some anonymized data available only we can easily put a JSFiddle together -

**Comment by NicolasRannou** [comment]
@FredChamp note that the MHD/RAW viewer is experimental, there might be orientation issues but due to the lack of testing datasets we left it as it is for now - testing against your data will help a lot in this matter, to make sure orientation is what it should be!

**Comment by FredChamp** [comment]
Ok thanks a lot @NicolasRannou ! It will be really helpful if you can provide a JSFiddle ;)
In the following WeTransfer link, you can find a DICOM image + a mhd/raw mask. 

https://we.tl/ubDa9Q0GU0

Bests,

**Comment by NicolasRannou** [comment]
Thx - @FredChamp which tool do you use to see DICOM + mask on top of each other?

**Comment by FredChamp** [comment]
I'm using ScanIP software but for web purpose, we currently try to implement AMI on our web platform.

Concerning DICOM visualization is possible to have a sequential slice loading as the Lify example: 
https://lify.io/watch/62116fb17e0444879845ea23fb1c105c

**Comment by NicolasRannou** [comment]
OK Thanks - would to happen to have smaller datasets in order to speed up the debugging process?

**Comment by FredChamp** [comment]
Sorry, all my DICOM are quite big...

**Comment by NicolasRannou** [comment]
Could you somehow just load 3 slices of the data in `ScanIP` and generate a "dummy" segmentation? And also send a screenshot of what you expect it to look like? I can load MHD properly but it doesn't overlay as expected so far... Not sure what is going on...

**Comment by FredChamp** [comment]
Thank you, Nicolas! 
I don't want to waste your time! So because I have STL, I can generate "mask" as you shown in the example.

Concerning DICOM loading, does AMI is able to do "sequential slice loading ?" as the following example:
https://lify.io/watch/62116fb17e0444879845ea23fb1c105c

**Comment by NicolasRannou** [comment]
Sorry for the late answer, was traveling for the past week with no internet connection -

That wouldn't be a waste of time :) that would be very helpful as other people are interested into it too but there is a lack of testing datasets on my side -

I addition, it should perform much better than the STL approach.

Sequential loading is possible but there are a couple of gotchas. Best way to make it would be to implement a new helper that would to the on-demand loading. With this approach, you can only look at the data in the "acquisition" direction and would need extra information about the data to be loaded.

Please open a new issue to chat more about this problem if you are still interested into it!

**Comment by FredChamp** [comment]
Hi Nicolas, 

Thank you for your help! 
Please find this WeTransfer link with a DICOM of 20 slices and the associated MHD/RAW mask. 

https://we.tl/cqNFt4fPQY

Concerning performances, it seems STL approach is better because it avoids mask loading (100 Mo). 
If the app is deployed on a server, it will decrease the amount of data stored for each patient case and will speed up the upload/load time.

**Comment by NicolasRannou** [comment]
awesome @FredChamp !

Dou you know if there could have been an issue while generating the first mhd/raw mask you provided? The offset seem strange but the new file you provided appears to work as expected.

**Comment by FredChamp** [comment]
Yeah it's possible, but cool if the new one works ;)

**Comment by NicolasRannou** [comment]
OK I'll close it then, please re-open if needed! @FredChamp
