### ISSUE TITLE
How to reference examples？

### ISSUE THREAD

**Issue by gjun-neusoft** [FNNDSC/ami#133]
Could you please explain to me:how to review and verify that,whether the examples in "examples" file are correctly referenced in "iframe tag" in index.html file or not?
Thank you very much!

**Comment by NicolasRannou** [comment]
Hi @gjun-neusoft  - can you elaborate a bit your question?

In `index.html` we add the example name: https://github.com/FNNDSC/ami/blob/dev/index.html#L217

This name must match the name of the directory where the example lives: https://github.com/FNNDSC/ami/tree/dev/examples/editor_draw, as well as all the files inside.

Does it help? What are you trying to achieve?

Thanks!

**Comment by NicolasRannou** [comment]
Closing - please re-open if needed
