### ISSUE TITLE
Data loading

### ISSUE THREAD

**Issue by Humphrey8** [FNNDSC/ami#135]
Hello,NicolasRannou

1. I would like to know the overall design concept of the data loading module.
2. How do the remote server's image files load to the local browser?
3. Are the image files on the remote server loaded completely into the local client? Or partially loaded into the local browser client?

Thank you very much. Looking forward to your reply.

**Comment by NicolasRannou** [comment]
Hi @Humphrey8 -

1- The idea is that the loader fetches "files" from a given "url". We get the response as an **array buffer**. Depending on the file type (we guess file type from file name), we use the proper parser to parse the array buffer. The parser returns a series > stack > frame structure.

2- Regular Fetch request with polyfills if not supported by browser. (https://developer.mozilla.org/en/docs/Web/API/Fetch_API)

3- We load it totally, all the data is available on the client.

Does it help? Do you have any specific question or concern?
Thanks!

**Comment by Humphrey8** [comment]
First thank you for your reply, I have some other questions:
1.If a group of CT images are stored on a remote server-side. The volume is 700M or greater .In this way ,it is necessary to load all the images,Which will take a long time in the images transmission. For the network of poor broadband, how to deal with this approach?
2. How does this large volume of data be visualized on the mobile side?

**Comment by NicolasRannou** [comment]
1. So if you use the AMI loaders, the "load" promise will resolve when all the data is fetched so from there you can do whatever you want. Slow data fetching should not have any impact on anything else. The promise is asynchronous so no big deal (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise). Does it answer your question?
2. It would work if the mobile device has enough RAM to hold all the data, if not WebGL will crash - After, depending on your application needs there are ways to reduce the memory footprint but comes with trade offs-

**Comment by Humphrey8** [comment]
Fetch is committed to replacing the XMLHttpRequest of the current remote resource communication. However, you  use ajax and fetch at the same time , I can not understand it? Can you explain in detail? Thank you

**Comment by NicolasRannou** [comment]
You are right I got confused we do not use fetch at this point - as you said in the loaders we use XMLHttpRequest, which is a shame, but the the "fetch" API do not allow to get "progress" event and there was no easy way to get download progress at the time.

It seems things are now getting better as stream is slowly getting integrated in major browsers - https://jakearchibald.com/2016/streams-ftw/

**Comment by NicolasRannou** [comment]
Closing - please re-open if needed!
