### ISSUE TITLE
Pre-processing

### ISSUE THREAD

**Issue by jinchengxiaoge** [FNNDSC/ami#136]
Hi ,NicolasRannou
I'd like to consult  you some questions that i do not understand .
For the preprocessing section.
1.What is the purpose of presrocessing?
2.Which algorithm is used ?
Hope to get your support and advice!

**Comment by NicolasRannou** [comment]
@jinchengxiaoge can you please elaborate a bit? which pre-processing? is your question related to AMI at all?

**Comment by jinchengxiaoge** [comment]
I mean the following part of the code。

   let series = loader.data[0].mergeSeries(loader.data)[0];
    loader.free();
    loader = null;
    let stack = series.stack[0];
    stack.prepare();  	  
    stack.pack();

**Comment by NicolasRannou** [comment]
```
// Loader returns an array of series per file (in a case a single file contains multiple series)
// If we load "file1.dcm" and "file2.dcm",
// loader contains: [series from file 1, series from file 2]
// series from file 1 contains stacks from file1
// stacks from file 1 contains frames from file1
// we call "mergeSeries" to group series, stacks and frames from file 1 with the ones from file 1
// after that series contains a proper series > stack > frame structure with no data duplication
let series = loader.data[0].mergeSeries(loader.data)[0];
// we get the first stack from the series
let stack = series.stack[0];
// we compute useful information such as world to data transforms, dimensions, origin, etc.
stack.prepare();
// we pack the raw pixel datas into a uint8 texture so we can pass it to the GPU
stack.pack();
```

Does it make sense?

**Comment by NicolasRannou** [comment]
Closing for now - please re open if needed

**Comment by jinchengxiaoge** [comment]
series from file 1 contains stacks from file1
stacks from file 1 contains frames from file1
we call "mergeSeries" to group series, stacks and frames from file 1 with the ones from file 1

I'm sorry to bother you again . 
I don't underdtand .  Can you  explain for me in detail ?  Thank you very much.

**Comment by NicolasRannou** [comment]
Sure - we can have 3 files that contain the following information:
```
file 1:
series A >  stack A > frame A
                     > frame B

file 2:
series A > stack A > frame C

file 3:
series B > stack B > frame B
```

When we load the 3 files, we get 3 'series' arrays containing the series/stack/frame structure for the file.

We then merge the 3 arrays so in our example above, frame C (from file 2), is located in the same stack as frame A and frame B, as it belongs to the same stack.

Structure after merge:
```
series array:
series A >  stack A > frame A
                     > frame B
                     > frame C
series B > stack B > frame B
```

Does it help?

Thanks

**Comment by jinchengxiaoge** [comment]
Hello, for this piece of content, is there an expression of integrity? What is its purpose?
