### ISSUE TITLE
helperslocalizer not included in the browserify build - ami.js

### ISSUE THREAD

**Issue by au84** [FNNDSC/ami#142]
The project structure is exactly the same. however the bowserify build does not include helpers.js ?

Helpers.js imports 
```
/** * Imports ***/
import ShadersUniform from
  '../shaders/shaders.localizer.uniform';
import ShadersVertex from
  '../shaders/shaders.localizer.vertex';
import ShadersFragment from
  '../shaders/shaders.localizer.fragment';
```

ami build instructions 

```
import Cameras from './cameras/cameras';
import Controls from './controls/controls';
import Core from './core/core';
import Geometries from './geometries/geometries';
import Helpers from './helpers/helpers';
import Loaders from './loaders/loaders';
import Models from './models/models';
import Parsers from './parsers/parsers';
import Shaders from './shaders/shaders';
import Widgets from './widgets/widgets';

const pckg = require('../package.json');

export default{
  Cameras,
  Controls,
  Core,
  Geometries,
  Helpers,
  Loaders,
  Models,
  Parsers,
  Shaders,
  Widgets,
};

window.console.log(`AMI ${pckg.version} ( ThreeJS ${pckg.config.threeVersion})`);" 
```

**Comment by NicolasRannou** [comment]
Which version of AMI are you using? NPM? #dev from Github?
 
The NPM build is "out of date" and will be updated as soon as we cut off a new AMI release. (still want to cleanup the stack model that has gotten out of control :) )
From the snippet you added, seems included properly and it does appear to be there in the #dev build from Github...

**Comment by au84** [comment]
i think it is AMI 0.0.15  

"dependencies": {
  "ami.js": "0.0.15",
  "babel": "^6.23.0",
  "babel-preset-es2015": "^6.24.1",
  "bootstrap": "^3.3.7",
  "browserify": "^14.3.0",
  "jquery": "^3.2.1",
  "material-design-lite": "^1.3.0",
  "node-dir": "^0.1.16"
  }

**Comment by NicolasRannou** [comment]
yes, so please try instead:
```
"dependencies": {
  "ami.js": "FNNDSC/ami#dev",
  "babel": "^6.23.0",
  "babel-preset-es2015": "^6.24.1",
  "bootstrap": "^3.3.7",
  "browserify": "^14.3.0",
  "jquery": "^3.2.1",
  "material-design-lite": "^1.3.0",
  "node-dir": "^0.1.16"
  }
```

**Comment by au84** [comment]
its still the same nic. its just the Helperslocalizer that doesn't get built everything else does ?

**Comment by NicolasRannou** [comment]
hmm it should - did you remove "ami.js" directory in the "node_models" directory before running "npm install"? Sometimes npm doesn't update packages properly..

**Comment by au84** [comment]
ohh - lemme try that mate. Cheers

**Comment by au84** [comment]
nic - i removed the ami.js directory from the node modules dir. Then ran npm install ( with the updated package.json "ami.js": "FNNDSC/ami#dev", ). The ami.js in the build folder under node_modules/ami.js/build/ami.js  is also not having helperslocalizer. 
[ami.js.zip](https://github.com/FNNDSC/ami/files/1031286/ami.js.zip)

**Comment by NicolasRannou** [comment]
How do you try to access the localizer from your app?

**Comment by au84** [comment]
var HelpersLocalizer = AMI.default.Helpers.Localizer;
<img width="539" alt="screen shot 2017-05-26 at 14 15 56" src="https://cloud.githubusercontent.com/assets/14296830/26487633/e358bf3e-421d-11e7-8753-55138d177f0a.png">

**Comment by NicolasRannou** [comment]
Strange - can you share a bit more code and print the content of "AMI.default.Helpers"?

**Comment by au84** [comment]
so what i have done is put the quad view code in a mpr.js file. In the quad view code you have used the helperlocalizer, that is where i get this construct error because when the code goes looking for helpers localised in the built ami.js file - it can't find the helperslocalizer. ami.default.helper attached. 
[helpers.js.zip](https://github.com/FNNDSC/ami/files/1031319/helpers.js.zip)

**Comment by NicolasRannou** [comment]
Please have a look at this fiddle where I just create a localizer as a test:
http://jsfiddle.net/eew73bsd/6/

**Comment by NicolasRannou** [comment]
Seems you are using an older ami version(not 0.16-dev). Does it print in the console which version of AMI you are using?

It should print something like:
```
AMI 0.0.16-dev ( ThreeJS r83)
```

**Comment by au84** [comment]
it is 0.0.16-dev 

<img width="550" alt="screen shot 2017-05-26 at 14 35 25" src="https://cloud.githubusercontent.com/assets/14296830/26488308/9bce7b60-4220-11e7-90f7-ecd6843736f8.png">

**Comment by au84** [comment]
hey - i had not included the Localizer in the Helpers.js file. Thanks for pointing that out. When i matched the code that line was missing - added that now and it is working - cheers
