### ISSUE TITLE
viewer shrunk in Chrome on android 

### ISSUE THREAD

**Issue by svabhishek29** [FNNDSC/ami#145]
The ami.js viewer used to work well on Chrome on android, however since the past few days the viewer does not load properly on chrome on android.

The same works perfectly on Chrome on iPhone.

Load Lesson 3 from your example on chrome on iPhone and chrome on Android.

**Comment by NicolasRannou** [comment]
Hmm can't reproduce, which version of Chrome are you using?

**Comment by svabhishek29** [comment]
Chrome version of Android: 58.0.3029.83.

**Comment by svabhishek29** [comment]
we were checking out cornerstone webgl render and found that in the mobile view it is getting clipped as well in android chrome, but in the desktop view is rendering properly. I it possible that issue could be coming in from cornerstone in AMI?

**Comment by NicolasRannou** [comment]
Hmm if same happens in cornerstone it is either related to your app or chrome...

What do you mean by clipped?

**Comment by svabhishek29** [comment]
the renderer is created only at the bottom left corner instead of the entire screen as we are asking it to using setsize. initially nothing is visible but when we try to zoom the view then the image appears in the bottom part.
please see the image below for reference. the image is visible only at the bottom corner and i try to move it, the image moves out of view.
it looks like as if the renderer is only coming in that part.
I am not sure if it is the app problem as the page is responsive and it is working properly in desktop chrome but this problem comes when same page is rendered in chrome android.
![screenshot 05-jun-2017 9_28_30 pm](https://user-images.githubusercontent.com/11541547/27031906-dada346c-4f8f-11e7-8b84-b4b74b7ccbc7.png)

**Comment by svabhishek29** [comment]
The issue was because of the buffer memory in webgl for mobile devices, the line 

var renderer = new THREE.WebGLRenderer({
    antialias: true,
  });

was the one causing the problem

For mobile devices which cant handle the antialias, just use 

var renderer = new THREE.WebGLRenderer();

This will solve the problem

**Comment by NicolasRannou** [comment]
wow good catch @svabhishek29 !
