### ISSUE TITLE
(fetch + parse + add to array

### ISSUE THREAD

**Issue by jinchengxiaoge** [FNNDSC/ami#147]
I don‘t ’ understand  the specific implementation of the mechanism inside the (fetch + parse + add to array) . Can you explain for me in detail ? Thank you very much.

**Comment by NicolasRannou** [comment]
@jinchengxiaoge 

**fetch:** list all files we want to load.
**parse:** parse every file to be loaded individually. It returns a series > stack > frame structure.
1 file can hold multiple frames.
**add to array**: the series > stack > frame structure for each loaded file is stored in an array. We usually then "merge" the series from this array to avoid duplicates and join frames than belong to the same stack.

Please let me know if you have more questions -
