### ISSUE TITLE
bepainting in the result of volume Rendering

### ISSUE THREAD

**Issue by hexingyang** [FNNDSC/ami#149]
Hi, @NicolasRannou 
I have an issue that why your volume Rendering(a brain) in lesson 06 is colorful. However, the result which I rebuild just has white and black.
Do you have some preprocessing in your nii file?
https://cdn.rawgit.com/FNNDSC/data/master/nifti/eun_brain/eun_uchar_8.nii.gz
And how can I put color on my result in different part by ami.
Looking forward to your reply.

**Comment by NicolasRannou** [comment]
@hexingyang the only preprocessing that happened to this data step was "Skull stripping".

To color the data, you should use LUTs as we do in [1].

[1] - https://fnndsc.github.io/ami/#vr_singlepass

**Comment by hexingyang** [comment]
Hi, @NicolasRannou . I have known how to colour the volume by LUT. Now I hvae a new issue.
I want to clip the model by a plane. I found that the material of volume is 'MeshStandardMaterial' in your demo #2 which clip brain. Using 'MeshStandardMaterial' on volume can be success to clip the model in my demo.
However, the material of volume in demo #6 is 'ShaderMaterial'. I add the attribute of clippingPlanes on the  material is invaild.  I guess some errors occur on the 'ShaderMaterial'. 
I want to know how to clip the volume in demo #6. Looking forward to your reply.

**Comment by NicolasRannou** [comment]
Please open a new issue if you have a different question :)
