### ISSUE TITLE
'rm' error in windows when trying 'yarn run example <example name>' in the ami repository. 

### ISSUE THREAD

**Issue by Doomedfajita** [FNNDSC/ami#155]
![image](https://user-images.githubusercontent.com/15896687/27657105-7a79b584-5c19-11e7-982c-4ed83b1d0ddb.png)

Every time I execute 'yarn run example <example name>' it throws this error.  The same result occurs with yarn run lesson <lesson number>.  Does anyone know what 'rm' is?  

I ran 'npm install ami' and installed ami into a folder "JavaScript App".  Yarn is also up to date.  I also updated the local repository from the master.

![image](https://user-images.githubusercontent.com/15896687/27657296-32954c8c-5c1a-11e7-92fe-935072e6d836.png)

Thank you for any help!!

**Comment by NicolasRannou** [comment]
Thanks for opening the issue @Doomedfajita 

Got to say I never tried it on windows :/

"rm" is used in unix to "remove" the target directory. Windows doesn't know about it and the way to go is actually to replace `rm` in the `package.json` file by `rimraf`:
https://github.com/FNNDSC/ami/blob/dev/package.json#L59

That being said new issues may pop up as I never tested it (originally was only targeting unix systems.)

**Comment by NicolasRannou** [comment]
Next, all the directory creation and path commands should be adapted with the "fs" and "path" node packages.

Another solution is to use the built-in shell for windows.
https://msdn.microsoft.com/en-us/commandline/wsl/about

Probably good to fix anyway but will not happen in the next weeks..

**Comment by Doomedfajita** [comment]
Thank you so much for the response!! I'll try to replace those commands!
Should I post my fix on the thread if I get it to work?  Thanks again!

**Comment by NicolasRannou** [comment]
No problem!

Best option is to submit a pull request once you manage to get it working!

Thanks!

**Comment by Doomedfajita** [comment]
Hey Nicolas!

Sorry to bother you again - I switched to linux (ubuntu) but still can't
quite get it to work.  I'm super new with linux so this error might be easy
to fix:

module.js:471
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>
(/home/sead/Desktop/ami/ami/scripts/router.js:1:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I'm running Ubuntu 14.04 64 bit.

I also opened an issue on github.

Thank you again!!
Sead

**Comment by NicolasRannou** [comment]
Seems related to #164

**Comment by NicolasRannou** [comment]
Closing for now since you now use Linux - please re open if needed
