### ISSUE TITLE
Migrate from Browserify to Webpack3

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ami#156]
https://rollupjs.org/

**Comment by NicolasRannou** [comment]
https://github.com/rollup/rollup-plugin-babel

**Comment by Flos** [comment]
Why not webpack2 ?
https://gist.github.com/forabi/2a538b263d0f1fe5f041

**Comment by NicolasRannou** [comment]
Yes actually last time I checked webpack didn't have tree shaking but it seems to now support it.

Not quite sure is the best option for a library.

Any thought?

**Comment by NicolasRannou** [comment]
webpack 3 may actually be a good candidate as it provides scope hoisting:
https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

In my understanding, webpack is really good to serve things "on-demand" whereas rollup is more about providing small / fast bundles.

**Comment by RusinovAnton** [comment]
I would like to take this one, should I?

**Comment by NicolasRannou** [comment]
@RusinovAnton that'd be awesome - in general the current scripts need to be revisited for this project, here are the things we want:

* build ami.js 
* build ami.min.js
* build independently examples from the "example" repo. The end goal is to use `webpack-dev-server` to serve a single example for development purpose. Ideally hot replacement would kick in for great developer experience.
* run tests

Important thing to keep in mind is that AMI still needs babel polyfills but we are willing to get rid of it sooner than later.

**Comment by NicolasRannou** [comment]
@RusinovAnton see #194 related issue - please do not hesitate if you have any questions!

**Comment by NicolasRannou** [comment]
closed by #195

**Comment by NicolasRannou** [comment]
Quick question? I ran the analyze script and it seems that THREE.JS is taking soooo much room. Any clue why that would be happening? We only import very few THREE.JS packages and the rest should be left out if I am not mistaking... :/
