### ISSUE TITLE
orient camera orthographic to resliced images

### ISSUE THREAD

**Issue by svabhishek29** [FNNDSC/ami#161]
Can you please help us in orienting the orthographic camera orthogonal to the resliced images. we are able to reslice the stack to the required direction but the camera is still in the old direction.

we need the camera to be orthogonal to the resliced set. the direction can change based on the requirement so we should be able to do it dynamically. 

It would be a great help if you can explain us how to set the position of the camera to be orthogonal dynamically

Thanks

**Comment by NicolasRannou** [comment]
Hi @svabhishek29 , that may already work, with some hip cups regarding the auto fit. (#97)

What you have to do is call init (https://github.com/FNNDSC/ami/blob/dev/src/cameras/cameras.orthographic.js#L55) with the right x, y and z cosines and you should be all set.

* x cosine: direction to the right of the slice
* y cosine: direction to the top of the slice
* z cosine: direction orthogonal to the slice

Do you have a jsfiddle by any chance?

**Comment by svabhishek29** [comment]
the link for js fiddle https://jsfiddle.net/3tcLb309/6/

We have just used the lesson 3 js fiddle and added the code that does the re slice for now. We are not able to calculate the x cosine, y cosine, z cosine, as in we are not understanding how to calculate the values.

is it possible to get the stack to slice in the same direction so that we can move the index slider and get the stack to move in the same direction? instead of the way right now how it is in the example (as in for one image instead of stack)

**Comment by NicolasRannou** [comment]
@svabhishek29, that is a bit messy but see how we compute v1, v2 and normal:

https://jsfiddle.net/3tcLb309/13/

**Comment by svabhishek29** [comment]
thanks @NicolasRannou. The information you provided was helpful
