### ISSUE TITLE
Yarn run example error Ubuntu

### ISSUE THREAD

**Issue by Doomedfajita** [FNNDSC/ami#164]
Hi!

I keep getting this error when attempting to "yarn run example <example_name>":

module.js:471
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sead/Desktop/ami/ami/scripts/router.js:1:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I'm running Ubuntu 14.04 64 bit.  

I installed shelljs - "sudo npm install -g shelljs" successfully.

Any help would be much appreciated!!!!

**Comment by NicolasRannou** [comment]
Can you please provide all the commands you typed to install AMI?

**Comment by NicolasRannou** [comment]
Googling around, it may be at NPM misconfiguration on your machine.

**Comment by NicolasRannou** [comment]
You shouldn't have to install "shelljs", it is already part of the NPM dependencies (https://github.com/FNNDSC/ami/blob/dev/package.json#L89)

**Comment by Doomedfajita** [comment]
The commands are as follows, after I installed node and yarn :

git clone https://github.com/FNNDSC/ami.git

cd ami

yarn run example geometries_slices

**Comment by Doomedfajita** [comment]
And I figured that shelljs came packaged, I couldn't find any way to remedy
it though.

**Comment by Doomedfajita** [comment]
I'm running Ubuntu in a virtual machine, could that be an issue?

**Comment by NicolasRannou** [comment]
@Doomedfajita , it seems you are missing one step during installation:

```
$> git clone https://github.com/FNNDSC/ami.git
$> cd ami
$> yarn run example geometries_slices
```

**Comment by Doomedfajita** [comment]
I'm sorry to be a bother - which step would that be?   It seems as though
they are the same.

**Comment by NicolasRannou** [comment]
You didn't run 'yarn install --ignore-optional'

**Comment by Doomedfajita** [comment]
I figured it out!  Thank you for all your help.  I originally had included
the "yarn install --ignore-optional", but I didn't realize yarn was using
an older version (0.22).  It kept throwing an error about --ignore-option
not a valid command.  I updated it to 0.275 manually, and then used the
instructions and it worked!
