### ISSUE TITLE
models.frame.js spacingXY

### ISSUE THREAD

**Issue by wjyoblleh** [FNNDSC/ami#166]
first element of PixelSpacing is row spacing,second element is column spacing.
http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_10.7.html#figure_10.7.1.3-1

**Comment by NicolasRannou** [comment]
Good catch, hopefully the fix is easy - @wjyoblleh would you have an anonymized dataset for testing?

**Comment by wjyoblleh** [comment]
[IM-0001-0001.dcm.zip](https://github.com/FNNDSC/ami/files/1147228/IM-0001-0001.dcm.zip)

**Comment by NicolasRannou** [comment]
@wjyoblleh is it OK to use this file for AMI's testing suite?

**Comment by wjyoblleh** [comment]
it's ok.i've used this dicom file in http://jsfiddle.net/gh/get/library/pure/fnndsc/ami/tree/master/lessons/03#run
