### ISSUE TITLE
Dotted line problem

### ISSUE THREAD

**Issue by jinchengxiaoge** [FNNDSC/ami#168]
Hello,NicolasRannou

![qq 20170727101506](https://user-images.githubusercontent.com/24455151/28651484-b8992758-72b4-11e7-9822-844179b0a88c.png)

How to remove the dotted line in the figure above or fix it ?
Thank you very much. Looking forward to your reply.

**Comment by NicolasRannou** [comment]
so the slices in the 2D and 3D views are linked so you have a couple of solutions:

1- Turn off the "dotted lines":
```
// pseudo code
stackHelper -> canvasWidth = -1
stackHelper -> canvasHeight = -1
```

2- In rendering loop, adjust the canvas size before rendering the scene
```
// pseudo code

// renderer 2d
stackHelper -> canvasWidth = renderer2d.width
stackHelper -> canvasWidth = renderer2d.height
renderer2D.render(scene2d, camera2d);

// render 3d
stackHelper -> canvasWidth = renderer3d.width
stackHelper -> canvasWidth = renderer3d.height
renderer3d.render(scene3d, camera3d);
```

**Comment by NicolasRannou** [comment]
Please re-open if needed
