### ISSUE TITLE
Quadview example not working on Firefox

### ISSUE THREAD

**Issue by YorkeUtopy** [FNNDSC/ami#171]
#### Steps to Reproduce
Open https://fnndsc.github.io/ami/#viewers_quadview on Firefox.

#### Expected Results
The Quadview renders correctly

#### Actual Results
Nothing renders, errors regarding WebGL and threejs rendering arise.

### Browsers Affected
- [ ] All
- [ ] Chrome
- [ X ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- AMI: v0.0.17
- THREEJS: v r86

**Comment by NicolasRannou** [comment]
Thanks for reporting the issue @YorkeUtopy , it seems I broke the styling so should be an easy fix!

- sorry for the late answer I was travelling with no internet access.
