### ISSUE TITLE
[Quadview example] Localizer positions not updated correctly on 2D views

### ISSUE THREAD

**Issue by YorkeUtopy** [FNNDSC/ami#172]
Hello, NicolasRannou

While fiddling with the Quadview example, I have found that the updateLocalizer() methods does not work as expected when the double click event happen. Ideally, I would want that when I double click on any of the 2D views, the crosshair for that slice (the other 2D view slices), centers on the mouse pointer. That does seem to work on the 3D view as indeed the 3 planes intersect at the mouse pointer, but the crosshairs are not updated correctly on the 2D view (also you can reproduce the issue while scrolling through some of the 2D views, the crosshairs on the other planes are not shown correctly).

Do you have any idea on how to fix this? I reckon it would be pretty easy but I cannot find documentation on how the localizer works, or what does it even do.

Thank you very much!!

**Comment by NicolasRannou** [comment]
Thanks for reporting the bug, it use to work so I probably broke things in a previous commit - will fix it shortly @YorkeUtopy
