### ISSUE TITLE
Stack bounding box wrong with negative world coordinate

### ISSUE THREAD

**Issue by leht** [FNNDSC/ami#181]
Hello,
I've found a bug with model.stack.js worldBoundingBox() function. You use:
    let bbox = [
      Number.MAX_VALUE, Number.MIN_VALUE,
      Number.MAX_VALUE, Number.MIN_VALUE,
      Number.MAX_VALUE, Number.MIN_VALUE,
    ];

But the Number.MIN_VALUE represents the smallest POSITIVE numeric value representable in JavaScript, it equals 5e-234, nearly 0 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_VALUE).
In my case, the max z world coordinate is negative -> cause the worldBoundingBox() function returns 5e-234 instead of that negative value. It causes the camera's box is wrong & other consequences.
I think the fix is simple:
let bbox = [
      Number.MAX_VALUE, -9999,
      Number.MAX_VALUE, -9999,
      Number.MAX_VALUE, -9999,
    ];
-9999 is enough in my case.

**Comment by NicolasRannou** [comment]
Hi @leht , it should be fixed by https://github.com/FNNDSC/ami/commit/39372b1e90469d621330c93747d6cb5454d26542

Which verison of AMI are you using?

**Comment by NicolasRannou** [comment]
Closing as inactive - please reopen if needed!

**Comment by leht** [comment]
Hello, sorry for late reply. I was out of office for couple of weeks.
Yes, this issue is fixed with current version of AMI.
Thank you!
