### ISSUE TITLE
Expose all classes exports at top level

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ami#183]
for instance, export  LoaderVolumes instead of Loaders.Volumes.

That allows us to use named imports:
```
import {LoaderVolumes} from 'ami.js';
```

otherwise it is pretty chaotic:
```
import AMI from 'ami.js'

...
const LoaderVolumes = AMI.Loaders.Volumes;
```

Main benefit will be at compilation time where bundler will only import the required deps (LoaderVolumes) instead of the full package.

1 - ami.js
```
...
export * from './geometries/Geometries.js';
...
```

2- geometries.js:
```
...
export {GeometriesSlice} from './geometries.slice.js';
```

3- geometries.slice.js
```
class GeometriesSlice

...

export {GeometriesSlice}

**Comment by mlichwala** [comment]
Hello @NicolasRannou, I would love to tackle this. It looks like a lot of manual work but I was thinking about giving jscodeshift a chance for this. What do you think?

**Comment by marcinlichwala** [comment]
@NicolasRannou I was using wrong account in the comment above ;) I'll be working on this one from now on. Please let me know if it's alright.

**Comment by NicolasRannou** [comment]
that'd be great! I didn't know about `jscodeshift`, please do not hesitate if you have any question!

**Comment by marcinlichwala** [comment]
I actually have a question, Nicolas: 
Should make a pull request to the dev branch or master directly? It looks like some sort of gitflow which is a bit confusing to me in this case. Which branch should I apply my changes to first?

Thank you!

**Comment by NicolasRannou** [comment]
To the dev branch!

Thanks @marcinlichwala
