### ISSUE TITLE
Problem with window center/width values detection

### ISSUE THREAD

**Issue by okrad** [FNNDSC/ami#184]
Hi, it looks like ami can't detect the default values for windowCenter and/or windowWidth with some images and renders them completely black.

You can reproduce the problem using your live [demo viewer](https://fnndsc.github.io/ami/#viewers_upload) and uploading [this file](https://drive.google.com/file/d/0B5fsZbHlg4bLOTI2aDdXYXNncmM/view?usp=sharing) (tested with latest chrome and firefox).

As you can see from the screenshot, the windowWidth and windowCenter sliders are set at the maximum value, resulting in a "black square".
![selection_001](https://user-images.githubusercontent.com/939812/30229158-201725bc-94e1-11e7-9a85-64876173db35.png).

Do you have any suggestions?

Thank you

**Comment by NicolasRannou** [comment]
Does it look fine if you change the window level manually afterwards? (I do not have a computer to look at it right now)

I would look in the stack which are the min/Max and window/level values detected and track it down from there. I'd also compare it to desktop software to make sure it is alright...

Will let you know when I can look at it (probably not today)

**Comment by okrad** [comment]
Yes, if you change the levels it looks fine. 
I opened the exam in FSLView 4.0.1 and it looks fine too.

I tried hacking around the stack as you suggest, but I couldn't find the place where the calculations for the default value are made.

**Comment by NicolasRannou** [comment]
Thanks for reporting the bug - there was an issue in the window-level calculation.

This Nifti dataset has a slope that is different from 1. The slope was applied too many times resulting in incorrect window-level calculations:

https://github.com/FNNDSC/ami/blob/abf6d6e19cb68eddde670b030afe81ca5b472005/src/models/models.stack.js#L265

`this._minMax[1] - this._minMax[0]` is already scaled so the correct computation is:

```diff
 -    let width = this._frame[0].windowWidth || this._minMax[1] - this._minMax[0];
 -    this._windowWidth = this._rescaleSlope * width + this._rescaleIntercept;
 +    let width =
 +      this._frame[0].windowWidth * this._rescaleSlope || this._minMax[1] - this._minMax[0];
 +    this._windowWidth = width + this._rescaleIntercept;
```

**Comment by okrad** [comment]
Thank you, now it's working!
