### ISSUE TITLE
Load and visualize normalized NIFTI data

### ISSUE THREAD

**Issue by aalises** [FNNDSC/ami#185]
Hello,

I am trying to visualize a nifti image, its intensity values normalized ranging from [0,1] instead of a T1 image with intensity level 34000,42000, etc... However, I get the image rendered all black. I suspect it is some normalization/range issue... how do you load and visualize normalized images? Specifically I am trying to load this [FA Measures image](https://cdn.rawgit.com/aalises/ami-viewerData/1b52554d/FA.nii.gz;).

and a [fiddle](http://jsfiddle.net/f36r2t25/1/) ilustrating the issue (based on example 3 but changing the file to mine)
Cheers,

**Comment by NicolasRannou** [comment]
Hi @aalises -  thanks for the report

The issue in this case is that some voxels of the FA MEasurement have invalid intensities ("NaN") after being converted from ArrayBuffer to a typed array. I do not know why, could be many reasons.

It messes up the window level and the data being passed to the shaders among others.

I'll push a fix later today but I am a bit worried about the impact on performance - that may be something we want to look into later on -

![screen shot 2017-09-13 at 1 44 42 pm](https://user-images.githubusercontent.com/214063/30375674-bedb4808-9889-11e7-861b-cd336a93a8a4.png)
