### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by ZHANGneuro** [FNNDSC/ami#186]
I am trying the example of viewers_quadview.js,  it gives an error of Uncaught SyntaxError: Unexpected token import. Could you give any suggestion？ Thanks!
![snip20170914_7](https://user-images.githubusercontent.com/5019040/30419530-45d6fb2e-9969-11e7-92b5-7ddacc851697.png)

**Comment by NicolasRannou** [comment]
Oops I probably just broke it - checking now

**Comment by ZHANGneuro** [comment]
Thanks for replying me by 10 seconds

**Comment by NicolasRannou** [comment]
Does this one work for you: https://fnndsc.github.io/ami/#viewers_quadview?

Which platform/browser are you using?

I assume you run `npm run example viewers_quadview` to run it, correct?

**Comment by ZHANGneuro** [comment]
The link works, I am on Mac platform and using Chrome. 

I did not run npm.  I download the AMI package and upload it on server, the server is a Virtual server online with basic web environment installed like HTML, WAP, PHP ,    I only have limited permission to access the server, and the terminal and any command line tool is not available for me.

**Comment by NicolasRannou** [comment]
OK that is why, it needs build for those examples to work.

In your case you can just get the code from the `gh-pages` branch that is already compiled - that should be all you need -

**Comment by NicolasRannou** [comment]
https://github.com/FNNDSC/ami/tree/gh-pages

**Comment by ZHANGneuro** [comment]
Thanks a lot!!!

**Comment by NicolasRannou** [comment]
Please re-open if needed!
