### ISSUE TITLE
[Question/Issue] values not updated correctly when accessing stack Raw Data (segmentation LUT)

### ISSUE THREAD

**Issue by aalises** [FNNDSC/ami#187]
Hello!

I have a question/issue regarding how to access and modify the raw data content of a stack. Particularly, my scene is data + a freesurfer labelmap generated with the segmentationLUT, which can be seen on [this live fiddle](http://jsfiddle.net/2f4bL2w3/4/).

What I want to do is to modify the contents of the stack (as a drawing tool would do, for instance). To do so in the most basic way, I access the contents of the stack2 after the stack2.pack() line and try to change some values. For instance the segmentation label 7 (voxel value present on the stack).

```
stack2.prepare();
  // pixels packing for the fragment shaders now happens there
  stack2.pack();
  for(let i = 0; i < stack2._rawData[0].length; i++){
    if(stack2._rawData[0][i] != 7) stack2._rawData[0][i] = 0;
  }
  var textures2 = [];
```

When I do this everything turns to 0 (transparent), except the 7 label, which works as intended. HOWEVER, when trying to do other things such as:

``` 
 for(let i = 0; i < stack2._rawData[0].length; i++){
       stack2._rawData[0][i] = 7;
  }
  var textures2 = [];
```

which should turn the entire stack to one color (the one of the segmentation label number 7) or

``` 
 for(let i = 0; i < stack2._rawData[0].length; i++){
       if(stack2._rawData[0][i] == 0) stack2._rawData[0][i] = 6;
  }
  var textures2 = [];
```

Which should turn everything transparent to color label number 6 for instance, etc. etc. it is not working, everything turns transparent as the labelmap is not applied. The stack values are changed though, what can be the issue there? can it be due to the pixel packing, the shader, the model stack...? Which would be the best way to modify the contents of the stack/texture?

Cheers,

**Comment by NicolasRannou** [comment]
`_rawData` is the data to be passed to the shaders, encoded in `8 bits`.

The data you are looking is encoded in 32 bits (`stack2.bitsAllocated`). In order to directly update the "packed" _rawData, you'd have to do something like: 
```
   const value = 7;
   for(let i = 0; i < stack2._rawData[0].length; i+=4){
       stack2._rawData[0][i] =  (value) & 0x000000FF;
       stack2._rawData[0][i+1] = (value >>> 8) & 0x000000FF;
       stack2._rawData[0][i+2] = (value >>> 16) & 0x000000FF;
       stack2._rawData[0][i+3] = (value >>> 24) & 0x000000FF;
  }
```

That is a shortcut not to have to run "pack()" another time as it is expensive.

Depending on the format of the data you want to update, you would have to adjust the approach:
https://github.com/FNNDSC/ami/blob/dev/src/models/models.stack.js#L523

http://jsfiddle.net/2f4bL2w3/19/


For reference, I've been doing something similar in the past but somehow it seems very slow now:
https://fnndsc.github.io/ami/#editor_draw

(was much faster before :/)

Please re-open in needed -

**Comment by aalises** [comment]
Thank you very much for your quick answer! Refering to the editor_draw example, I have seen that it's slow on Chrome but not on Firefox (draws almost instantly on Firefox) :+1: . I suspect it has something to do with the context.getImageData() method...

**Comment by NicolasRannou** [comment]
Yes that is what I saw in the Chrome dev tools when I had a quick look at the issues but that is actually good if fast in Firefox - hopefully there is a good workaround or Chrome will fix it!

**Comment by aalises** [comment]
Hello @NicolasRannou ,

I have been fiddling around with the draw example. I have taken the example as it is and changed the data for the freesurfer labelmap (.css , .html , .js can be found on a .zip [here](https://transfer.sh/P1v0r/ExampleFreesurferEditor.zip) (would have made a fiddle but events were not working...)).

On this example I basically changed the data, get rid of the information panel (editorStats) and the segmentation labels that were before for simplicity, and assigned a known label value to the cursor (6), and a color, so basically you are editing the colormap adding the value label 6.

```
let cursor = {
  color: '#28c928',
  value: 6, //For testing purposes, we paint the segmentation number 6!
  size: 15,
  shape: 'round',
  segment: 'erase',
};

```
 Also in the mapCanvasToData function I changed the old line of updating the rawData for the workaround that you put above.

```

            if (oldValue != newValue) {
              // update raw data NEW
              stack2._rawData[rawDataIndex][inRawDataIndex] =  (newValue) & 0x000000FF;
              stack2._rawData[rawDataIndex][inRawDataIndex+1] = (newValue >>> 8) & 0x000000FF;
              stack2._rawData[rawDataIndex][inRawDataIndex+2] = (newValue >>> 16) & 0x000000FF;
              stack2._rawData[rawDataIndex][inRawDataIndex+3] = (newValue >>> 24) & 0x000000FF;
              //update raw data OLD
              //stack2.rawData[rawDataIndex][inRawDataIndex] = newValue;

              // update texture that is passed to shader
              textures2[rawDataIndex].image.data = stack2.rawData[rawDataIndex];// tex;
              textures2[rawDataIndex].needsUpdate = true;

            }
```

When editing, though, **nothing is drawn** below the cursor... only random pixels from random frames are drawn, it seems that there is an issue on the mapCanvasToData function, when getting the **inRawDataIndex**... maybe you know what causes this, the textureSize = 4096 maybe has changed or the coordinate changes are messed up (although I do not know, everything is exactly the same as the drawing example but the data...).

Cheers and thank you for your patience,

**Comment by NicolasRannou** [comment]
so therewere a couple of issues:

1- the voxel increment is 4  because we are in 32 bits:
```
            let voxelIndex = i
                            + j * stack2._columns
                            + k * stack2._rows * stack2._columns;
            voxelIndex *= 4;
```

2- get the old value:
```
            let oldValue =
              (stack2.rawData[rawDataIndex][inRawDataIndex + 3] << 24) |
              (stack2.rawData[rawDataIndex][inRawDataIndex + 2] << 16) |
              (stack2.rawData[rawDataIndex][inRawDataIndex + 1] << 8) |
              (stack2.rawData[rawDataIndex][inRawDataIndex]);
```

And that should be it.

Finally, I think `context.getImageData` should be moved out of the crazy i/j/k for loops:
-> Get all image data into an array at the very beginning of `mapCanvasToData`.
-> access the right index from array instead of `let pixel = <get right index>`.

**Comment by aalises** [comment]
Thank you very very much Nicolas!! Been bothered by that for quite the time, just an issue of bit packing then, phew.

Greetings,

**Comment by aalises** [comment]
Hello @NicolasRannou ,

I have been testing how the texture drawing is stored into the data array and if it is consistent with the coordinates etc. and I have a problem accessing the data from the labelmap. All the code can be seen 
[here](https://transfer.sh/oVc7G/ExampleFreesurferEditor.zip). Namely I have implemented this method on mouse move

```
function raycastLabelmap(event) {
      const canvas = event.target.parentElement;
      const id = event.target.id;
      const scene = sceneLayer0;
  
      if(typeof lutLayer1 == "undefined") return; //If no labelmap loaded, no point on raycasting it
   
      const mouse = {
          x: (event.clientX - canvas.offsetLeft) / canvas.clientWidth * 2 - 1,
          y: -((event.clientY - canvas.offsetTop) / canvas.clientHeight) * 2 + 1
      }
   
      const raycaster = new THREE.Raycaster();
      raycaster.setFromCamera(mouse, camera);
  
      const intersects = raycaster.intersectObjects(scene.children, true);
      if (intersects.length > 0) {
          let ijk = Utils.worldToData(
              stackHelper.stack._lps2IJK,
              intersects[0].point
          );
          let voxelValue = Utils.value(stack2, ijk);

          if (voxelValue != prevVoxelValue) {
              prevVoxelValue = voxelValue;
              let NameLabelmap = lutLayer1.segmentation[voxelValue];
              if (voxelValue !== 0 && typeof NameLabelmap != "undefined") {
                  document.getElementById("structure-info-label").innerHTML = "Structure name: <br>" + NameLabelmap['label'];
              } else {
                  document.getElementById("structure-info-label").innerHTML = "Structure name: <br> undefined";
  
              }
          }
      }
    }
```
Which raycasts the scene and returns the voxel value of the stack labelmap at a given ijk coordinate and gets the structure name when hovering over. It works perfectly on the segmentation loaded. However, when drawing a new segmentation, the stack labelmap value seems not to be updated correctly, as hovering the newly drawn texture do not show its corresponding structure, but seems that, although visually it is drawn, the values are not updated hence the getting the ijk value from the stack gives you the old value at that position even though the new labelmap is drawn correctly.

Do you know what that would be caused for? is it an issue on how do we put the new data into stack2 at the **mapCanvasToData** function?

**Comment by NicolasRannou** [comment]
Yes, the reason is that when drawing, we directly draw into the "stack.rawData". Its only purpose (at least yet) is to be sent to the GPU for visualization. The actual value of the data is not stored there. It is stored in the frame.pixelData.

In addition of updating the `stack2.rawData`, you have to update the value of the data stored in the frame (frame.pixelData) - see there how we use it to **get** data from a frame. (https://github.com/FNNDSC/ami/blob/dev/src/core/core.utils.js#L246-L254)

We will need something similar to **set** the data of the frame.

Does it make sense?
