### ISSUE TITLE
[bug] Problem displaying large NIFTI file

### ISSUE THREAD

**Issue by tarelli** [FNNDSC/ami#188]
The library seems to have a problem loading a bunch of NIFTI files (that work well in Amira), while we had no problems with others.
The NII not working can be downloaded [here](https://www.google.com/url?q=https%3A%2F%2Fs3.amazonaws.com%2Fpatient-hm-august-2017%2FBlockface%2FVolumes%2FHM_BLOCKFACE_VOLUME_512_ISOMETRIC.nii.gz&sa=D&sntz=1&usg=AFQjCNHfBDLb2uErNZc591Qju7ejvpzH7w).
After moving the camera I manage to see something on the 3D quadrant (in a buggy way) but nothing on the other quadrants, see few screenshots.
Other NIFTI files we are using have no problems. 
Is it a bug on the library? Is there some setting we should adjust?
Thanks!

![screen shot 2017-09-15 at 19 01 37](https://user-images.githubusercontent.com/81127/30496760-54d04ff6-9a48-11e7-862a-f76c7933f8a5.png)
![screen shot 2017-09-15 at 19 01 43](https://user-images.githubusercontent.com/81127/30496759-54b949b4-9a48-11e7-9765-f5f660bdb364.png)

**Comment by NicolasRannou** [comment]
Thanks for reporting the bug - can you try to load the data at https://fnndsc.github.io/ami/#viewers_upload ?

I do not have access to a computer right now! Thanks!

**Comment by tarelli** [comment]
Same there, nothing shows:
![screen shot 2017-09-15 at 20 24 36](https://user-images.githubusercontent.com/81127/30499840-f6b63924-9a53-11e7-96b1-b43e73557030.png)

**Comment by NicolasRannou** [comment]
Could you also please share a typical working dataset?
I think I found the issue in AMI but would expect a slightly different "display" of the problem, so I'd like to have another similar working dataset as a reference -

There are 512x512x512 (134M) 8 bits voxels that represent the data.
Right now we pass 4096x4096x7 = 117M 8 bits voxels to the GPU.

We need to apply some "smart packing" for the data and we will be able to pass about 500M 8bits voxels to the GPU. (Right now only the 16 bits datasets are smartly handled).

However, only about the first 30 slices seem to be displayed correctly and the rest just doesn't show - no error in console. That is strange as I'd expect about 90% of the data to be already visible (117M/134M) -

looking into it - Will keep you posted! Thanks!

**Comment by tarelli** [comment]
Thanks for looking into it @NicolasRannou, [here](https://s3.amazonaws.com/patient-hm-august-2017/MRI/IN+SITU+2008+T2-WEIGHTED/IN-SITU-2008-T2-WEIGHTED-ALT.nii.gz) is one that works (however some quadrants are rotated, we'll be fixing that data side).

**Comment by tarelli** [comment]
[This](https://s3.amazonaws.com/patient-hm-august-2017/Blockface/Volumes/HM_BLOCKFACE_VOLUME_1024.nii.gz) is an ever bigger one (1024) if it can help have more test data.

**Comment by tarelli** [comment]
hi @NicolasRannou any update on this? Thanks!

**Comment by NicolasRannou** [comment]
wow didn't realize so much time passed since you opened the issue sorry about that - been quite busy -

**Comment by tarelli** [comment]
@NicolasRannou thanks for looking into it, let me know if there's anything else I can do to help, it's a bit of a roadblock for us atm, cheers!

**Comment by tarelli** [comment]
@NicolasRannou hey Nicolas, any update on this? It would be good to have an idea of the timeline if it's something you can estimate, thanks so much!

**Comment by NicolasRannou** [comment]
Hi @tarelli - didn't have time to look at that since been quite busy at work on some tight deadlines -

I'd be happy to point you in how to implement that if you are interested -

Good new is that in theory you will also be able to load the 1024*1024*1024 as the data type is `unsigned char`.

What it (should) comes down to is:
1- pack 4 values per pixel
https://github.com/FNNDSC/ami/blob/dev/src/models/models.stack.js#L480-L482
https://github.com/FNNDSC/ami/blob/dev/src/models/models.stack.js#L544-L559
2- unpack in the shaders
https://github.com/FNNDSC/ami/blob/dev/src/shaders/helpers/shaders.helpers.texture3d.js#L34
should probably be: `offset = index - int(uPackedPerPixel)*indexP;`
https://github.com/FNNDSC/ami/blob/dev/src/shaders/helpers/shaders.helpers.unpack.js#L85
should probably be: `packedData[offset]` (not sure the syntax is valid)

**Comment by NicolasRannou** [comment]
That has been implemented
