### ISSUE TITLE
Volume Rendering Performance

### ISSUE THREAD

**Issue by Humphrey8** [FNNDSC/ami#190]
Hello,NicolasRannou
I met a problem when i ues the ami.js. In volume rendering, the browser often dies and shows a webgl problem that causes the browser to crash. Is there a good way to solve this problem?

**Comment by NicolasRannou** [comment]
Yes the current implementation is pretty GPU inte since - can you check the latest version of the VR example? The are a couple of trucks to improve the behavior (reduce the number of steps when user is interacting, and only render scene when needed)

**Comment by Humphrey8** [comment]
I do not understand the truck, can you explain to me?

**Comment by Humphrey8** [comment]
I can not open the latest vr example。

**Comment by NicolasRannou** [comment]
strange - which browser are you using? any message in the console?
https://fnndsc.github.io/ami/#vr_singlepass

**Comment by Humphrey8** [comment]
Google Chrome    61.0.3163.100

**Comment by Humphrey8** [comment]
![1](https://user-images.githubusercontent.com/26323700/31365831-5375d9d0-ada0-11e7-9b97-c7a319e3023b.png)
![2](https://user-images.githubusercontent.com/26323700/31365835-56808e0e-ada0-11e7-8150-9d2e67c55ec3.png)

**Comment by NicolasRannou** [comment]
there you can see 2 files are not be loaded:
`data.gui.min.js` and `stats.min.js`

Are you behind some specific firewall on in a specific region of the world?

**Comment by NicolasRannou** [comment]
What happens if you look at: https://fnndsc.github.io/ami/#geometries_slice

Does those files get loaded in this example?

**Comment by NicolasRannou** [comment]
Closing for now - please re-open if needed!
