### ISSUE TITLE
Deep cloning AMI Js objects

### ISSUE THREAD

**Issue by aalises** [FNNDSC/ami#192]
Hello,

I was wondering about the best way to clone AMI JS objects without reference (for instance, **models/stack** ). What I want to do is clone/copy an stack object to another variable without a reference, so when the original object is modified, the cloned one is not.  I have tried several javascript approaches but it seems that when I modify the ._rawData or PixelData of the object, the cloned object is modified as well......

Which would be the best way to clone a AMI JS object? is there a implemented way? or why is it not working in my case...

```
  stack2.prepare();
  // pixels packing for the fragment shaders now happens there
  stack2.pack();

 let stack2Original = $.extend(true,{},stack2);
//some changes to stack2 pixelData and RawData... and stack2Original is changed as well!

```

Greetings,

**Comment by NicolasRannou** [comment]
yes I guess that is the expected behavior with jQuery extend.

Something like that should work -
And the same for the pixelData of the frames.

Key is to use "slice" to make sure we are actually creating a new array.

```
 let stack2Original = $.extend(true,{},stack2);
stack2Original.rawData = [];
for (let i = 0; i< stack2.rawData.length; i++) {
  stack2Original.rawDat.push(stack2.rawData[i].slice(0));
}
```

**Comment by aalises** [comment]
Hello,

Thank you! it does work for the rawData. Extending it to the **pixelData** should be something like:

```
    for (var i = 0; i < stack2._numberOfFrames; i++) {
      stack2Original._frame[i]._pixelData = [];
      for (let j = 0; j< stack2._frame[i]._pixelData.length; j++) {
        stack2Original._frame[i]._pixelData.push(stack2._frame[i]._pixelData[j].slice(0));
    }
  }
  
```

It does not seem to work though, and putting something like 
```
stackLabelmapOriginal._frame[i] = $.extend(true,{},stackLabelmap._frame[i]);
```
does not work either...

**Comment by aalises** [comment]
Just looked at it again and seems like the issue is that the extend does not deep copy the frame objects or something like that... can't get to copy the pixelData without reference inside the stack2Original...

**Comment by NicolasRannou** [comment]
yes I guess it is just how this jQuery extend works -

I wouldn't use jQuery for this kind of operations anyway, maybe lodash is a better option - 
https://lodash.com/docs/4.17.4#cloneDeep

In the meanwhile, may just be easier not to try to make a deep copy and only "slice" arrays of interest.

my 2 cts

**Comment by NicolasRannou** [comment]
Closing for now - I see where that can be useful but not 100% sure if that should or not be part of AMI -

Did you resolve your issue?
