### ISSUE TITLE
the raycasting

### ISSUE THREAD

**Issue by Humphrey8** [FNNDSC/ami#197]
I can't understand the process of implementing the raycasting algorithm in AMI. Can you explain it
 in detail.Thank you

**Comment by NicolasRannou** [comment]
Can you please update content @Humphrey8 ?

**Comment by NicolasRannou** [comment]
which part don't you understand?

do you know the theory on ray casting volume rendering?
https://en.wikipedia.org/wiki/Volume_ray_casting

We do not do shading for now but I want to add it at some point!

**Comment by Humphrey8** [comment]
I know the theory on raycasting volume rendering.  
1. How to take sampling points in ami ? 
2. In the Compositing phase  the ami  uses the methodback-to-front or front-to-back ？ 
3. Is there any documentation for this section?

**Comment by NicolasRannou** [comment]
> How to take sampling points in ami ?
Not sure what you are asking

> In the Compositing phase the ami uses the methodback-to-front or front-to-back 
Front (near) to back (far)
https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.vr.fragment.js#L77-L82

> Is there any documentation for this section
No... it is all contained in there:
https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.vr.fragment.js

Please do not hesitate if you have any question of if you are looking for extra features

**Comment by NicolasRannou** [comment]
Closing for now - please do reopen if needed
