### ISSUE TITLE
[bug] Volume Rendering: Zoom inside the cube object

### ISSUE THREAD

**Issue by daron1337** [FNNDSC/ami#198]
### Description
Unable to zoom into the VR object. If the camera is inside the "cube", there's no rendering.

#### Live Demo
http://jsfiddle.net/gh/get/library/pure/fnndsc/ami/tree/master/lessons/06#run

#### Steps to Reproduce
Zoom into the VR "cube"

#### Expected Results
I'd like to be able to zoom the VR object without any limit

#### Actual Results
There's a limit about zooming distance

### Browsers Affected
- [x] All
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- AMI: v0.0.20
- THREEJS: r87

**Comment by NicolasRannou** [comment]
Sorry for the late answer I was traveling with no internet connection -

Yes I knew about this issue and there are 2 places I'd look into:
1- Ray direction got messed up 
https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.vr.fragment.js#L64

2- Start/end point are not correct
https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.vr.fragment.js#L73-L74

I'll let you know when I have a chance to dig into it!
