### ISSUE TITLE
quadview example doesn't work properly 

### ISSUE THREAD

**Issue by nis1** [FNNDSC/ami#204]
The example doesn't work well in any browser, or after deployment.

**Comment by NicolasRannou** [comment]
Thanks for reporting - appeared while testing a new build system -  will be fixed shortly.

FYI only the style is broken and adding:
```
body, html {
  height: 100%
}
```

fixes it -

**Comment by nis1** [comment]
I have tried to add it, but it didn't solve the problem

**Comment by NicolasRannou** [comment]
strange I could get it working - please hold on a bit, we will merge #195 very soon and everything will be back to normal!

**Comment by HerrVoennchen** [comment]
yep, @NicolasRannou  css fix did it. Have you include it already in your branch? otherwise I would put this in the PR as well.

**Comment by NicolasRannou** [comment]
OK let's add it in the PR so we can close all that at once - thanks

**Comment by NicolasRannou** [comment]
closed by #195
