### ISSUE TITLE
Loaders.Volume reading MHD image image spacing issue

### ISSUE THREAD

**Issue by ccchef** [FNNDSC/ami#207]
Please note that we do not have a `ami.js` tag on StackOverflow yet.
After asking help on SO, please open an issue with the link to the SO post so we get notified.

If you have privilegies to create a new tag on SO, please help us by creating the `ami.js` tag.

### Description

Hello,
I tried to load a .mhd/.raw 3D image using AMI. I used the AMI.default.Loaders.Volume class. The result is rather encouraging and I succeeded in displaying the 3D image volume. However, there is a small problem. It seems that the image size in the X and Y directions are inversed. I feel that it used imageSpacing[0] for computing the physical size in Y dimension and imageSpacing[1] for x-dimension. Since imageSpacing[0] doesn't equal imageSpacing[1], the display is not consistent with the actual object size. In our case, I see an elongated liver in the ultrasound image. When I switched the imageSpacing[0] and imageSpacing[1] in the mhd file, everything becomes normal. 
I think it may come from a bug of LoadersVolume. Could you please verify this? I put the mhd/raw images that I used in the attached file. A screenshot of the image is also available there.
[us4d_rai.zip](https://github.com/FNNDSC/ami/files/1430864/us4d_rai.zip)
![elongated_liver](https://user-images.githubusercontent.com/33158336/32226247-5285775c-be48-11e7-8e34-bc05aaa1adeb.jpg)

Thanks!

   

Yitian

### Browsers Affected
- [ ] All
- [ x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- AMI: v0.0.13
- THREEJS: vX.X.X

**Comment by NicolasRannou** [comment]
Related to #166

**Comment by NicolasRannou** [comment]
Thanks!

The problem was that AMI was interpreting X spacing as row spacing instead of column spacing in the MHD parser!

**Comment by NicolasRannou** [comment]
Can you please try to upload your data there: https://fnndsc.github.io/ami/#viewers_upload to confirm it works as expected?

Thanks!

**Comment by ccchef** [comment]
Thanks for the helpful response!
It seems that the link you provided above doesn't support MHD format. It only supports Dicom/Nifti/Nrrd images. I didn't succeed in uploading my Mhd image. 

Could you please look at this?
thanks!

Yitian

**Comment by NicolasRannou** [comment]
ES, just select both raw and mhd files while uploading, that should work! (tested here)

**Comment by ccchef** [comment]
Yes! It works now.
Thank you very much!

Yitian
