### ISSUE TITLE
[build] Failing to build on npm 

### ISSUE THREAD

**Issue by tarelli** [FNNDSC/ami#208]
Ami.js 0.2.0 is failing to build via npm due to:

```
[ERROR] npm ERR! git submodule -q update --init --recursive: fatal: remote error: access denied or repository not exported: /p/fonttools/code
[ERROR] npm ERR! git submodule -q update --init --recursive: Clone of 'git://git.code.sf.net/p/fonttools/code' into submodule path 'test/ttx/fonttools-code' failed
[ERROR] npm ERR! git submodule -q update --init --recursive: Failed to recurse into submodule path 'ext/pdf.js'
[ERROR] npm ERR! git submodule -q update --init --recursive:
[ERROR] npm ERR! git submodule -q update --init --recursive: fatal: remote error: access denied or repository not exported: /p/fonttools/code
[ERROR] npm ERR! git submodule -q update --init --recursive: Clone of 'git://git.code.sf.net/p/fonttools/code' into submodule path 'test/ttx/fonttools-code' failed
[ERROR] npm ERR! git submodule -q update --init --recursive: Failed to recurse into submodule path 'ext/pdf.js'
[ERROR] npm ERR! git submodule -q update --init --recursive:
```
I tracked the dependency, it comes from image-JPEG2000
```
ami.js@0.0.20
│ ├── dicom-parser@1.7.3
│ ├── image-JPEG2000@0.3.1 (git://github.com/ohif/image-JPEG2000.git#ed628f6ef0c505377179ce5c952cd7265c87e065)
│ ├─┬ jpeg-lossless-decoder-js@1.2.3
│ │ ├─┬ browserify@14.5.0
│ │ │ ├─┬ browser-pack@6.0.2
```

https://github.com/OHIF/image-JPEG2000/blob/master/.gitmodules

which depends on

https://github.com/OHIF/pdf.js/blob/master/.gitmodules

which fails because `git://git.code.sf.net/p/fonttools/code` doesn't exist anymore.

**Comment by NicolasRannou** [comment]
Thanks for reporting the bug, do you know if using the official `pdf.js` (https://github.com/mozilla/pdf.js) solves the issue?

What is strange though that we can compile the examples within AMI properly.. :/

**Comment by NicolasRannou** [comment]
Also did it use to work fine? if so, do you know when it started to break?

**Comment by tarelli** [comment]
@NicolasRannou at some point I think we worked, then we started working with a built js to have the latest. Few days ago I tried to go back to using npm and I found out that error. Not sure when it stopped working. Using the official pdf.js probably solves the issue given this commit https://github.com/mozilla/pdf.js/commit/d68eb153d3bbeab71311fde03c1eaf5036b2b7db

**Comment by NicolasRannou** [comment]
Can you please give a shot to the latest release? (0.0.21)

Please note the syntax will change from: `AMI.default.Loaders.Volume` to `AMI.VolumeLoader`!

Thanks for helping figuring this one out!

**Comment by aalises** [comment]
Hello!

The bug is still appearing when building ami.js (v0.0.22) with the pdf.js latest package found [here](https://www.npmjs.com/package/pdfjs-dist). Any workaround to that?

Cheers.

**Comment by NicolasRannou** [comment]
Would you have a minimal example I can git clone to reproduce by any chance?

**Comment by k1r0s** [comment]
@NicolasRannou 

To reproduce the issue just run

`npm install ami.js`

**Comment by NicolasRannou** [comment]
OK - I do the installation through yarn and it works there somehow, can you confirm?

``` bash

yarn add ami.js

```

**Comment by k1r0s** [comment]
ok, it works with yarn.. but still https://github.com/FNNDSC/ami/issues/231

**Comment by laurennlam** [comment]
Any other clue if we want to use ami.js in a package.json file ? I can't use yarn...
It seems that this bug isn't solved in the latest release.

**Comment by meawoppl** [comment]
I just ran into this as well....  npm requirements driven install:
```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated uglifyjs@2.4.11: uglifyjs is deprecated - use uglify-js instead.
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated uws@9.14.0: stop using this version
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! warning: templates not found /tmp/pacote-git-template-tmp/git-clone-ac4a98f7
npm ERR! warning: templates not found /tmp/pacote-git-template-tmp/git-clone-ac4a98f7
npm ERR! fatal: remote error: access denied or repository not exported: /p/fonttools/code
npm ERR! fatal: clone of 'git://git.code.sf.net/p/fonttools/code' into submodule path 'test/ttx/fonttools-code' failed
npm ERR! Failed to recurse into submodule path 'ext/pdf.js'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-12T23_27_56_101Z-debug.log
```

**Comment by meawoppl** [comment]
OIC, the backward dep from the jpeg2000 plugin seems to lean on a recently broken link to an unofficial repo for `fonttools`  I am going to try to pin that forward to see if it unbreaks stuff

**Comment by meawoppl** [comment]
Confirmed.  I can install all deps cleanly except:
```
        "image-JPEG2000": "OHIF/image-JPEG2000#master",
```

Which afaict is hung on this (missing) submodule.  I am going to fork this and see if I can fix it.

**Comment by meawoppl** [comment]
PR opened above.  Let me know if you have a contributor agreement or similar whatnot.

**Comment by NicolasRannou** [comment]
Thanks!
