### ISSUE TITLE
[help] Could you help me to set up the node server / browser connection to be able to run the examples and start coding?

### ISSUE THREAD

**Issue by YoneMoreno** [FNNDSC/ami#235]
Hello and thank you for your time 

I would like to ask for help because I have tried to use the library for first time AMI.js

 I have done the steps which are written in the Developer Corner:  $> git clone https://github.com/FNNDSC/ami.git $> cd ami $> yarn install

 And all looks good I have installed the dependencies and the library well.  

However when I start the server it says 'ERR_ADDRESS_INVALID"

The images which show console/browser output: https://stackoverflow.com/questions/48210312/using-ami-js-for-first-time-issue-when-starting-lessons

Could you help me please???

### Browsers Affected
- [ ] All
- [ X] Chrome
- [ X] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- AMI: v0.0.22

**Comment by NicolasRannou** [comment]
Where does it say:''ERR_ADDRESS_INVALID"'?

Which version of node, yarn and windows are you running?

**Comment by NicolasRannou** [comment]
@YoneMoreno what is you go to "localhost:8080" instead of "0.0.0.0:8080"?

**Comment by NicolasRannou** [comment]
(that solves it for me)

**Comment by YoneMoreno** [comment]
Hello NicolasRannou and thank you for your help.

I have node version v8.9.0, webpack version 3.7.1 and windows 8.1.

I have posted more images because of it looks like webpack cannot resolve some files when running yarn example 03.

https://stackoverflow.com/questions/48210312/using-ami-js-for-first-time-issue-when-starting-lessons


Also I would like to ask you NicolarRannou if I would like to use the library into my own development to make a web appliaction using it, would I only need to include the script as you state on the description after threejs?

Thank you for your help.

**Comment by YoneMoreno** [comment]
Thank you for your help I got it working using IDE built-in server.
