### ISSUE TITLE
[Question] Volume rendering with TEXTURE_3D

### ISSUE THREAD

**Issue by JorgeVA1994** [FNNDSC/ami#236]
Hi everyone,

I have to load and render some 3D textures generated from DICOM images. I should use TEXTURE_3D but I don't know if there are some limitation with this kind on textures in webgl2. If there are some hard limitation (small size, low maximum memory supported or something like this) I can workaround with textures 2D and use this toolkit but I should work with 3D textures. 

Any suggestions would be welcome!
Thank you!

**Comment by NicolasRannou** [comment]
Hi @JorgeVA1994  - there are some hard limitation but those are device specific (an average phone is much less capable that the latest GPU).

Main reason we do not use #D textures are:
* only 40% of devices support it yet (https://webglstats.com/webgl2)
* THREEJS doesn't provide the hooks for it yet

Hope that helps.

Happy to try to help if you want to try to add such a feature in AMI or work on the Volume rendering on general!

Please re-open if needed!
