### ISSUE TITLE
[Help] Trying to run examples in local it does not work

### ISSUE THREAD

**Issue by YoneMoreno** [FNNDSC/ami#237]
Thank you for your help reading this:

Hello I would like to have some kind help to be able to run AMI's examples in local. I am currently trying to load the uploader example. The problem I have encountered is that imports look like are not properly set, even if I try to set them up with IDE's help, when I execute the index.html the browser launchs exceptions related to imports.

**I do explain this issue very detailed and with images here:**
https://stackoverflow.com/questions/48287911/javascript-trying-to-run-amijs-examples-in-local-it-does-not-work

Thank you for your help.

**Comment by NicolasRannou** [comment]
It seems you are not starting the development server as you should. Added suggestion in stackoverflow!

Please re-open if needed!
