### ISSUE TITLE
[bug] Volume Render dosen't respect position correctly

### ISSUE THREAD

**Issue by meawoppl** [FNNDSC/ami#239]
### Description
VolumeRender fails if not positioned at the origin of the scene.

#### Live Demo
http://jsfiddle.net/mr4ub2Lv/

#### Steps to Reproduce
Before adding `vrHelper` to the scene, shift its position.

#### Expected Results
Shifted location in the scene.

#### Actual Results
Shader weirdness:
![image](https://user-images.githubusercontent.com/579782/35189645-355ea40e-fe04-11e7-8e5c-85fa311f09f6.png)

### Browsers Affected
- [X] All
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
Current

**Comment by NicolasRannou** [comment]
Hi @meawoppl,

I'll look into it next week! That may help in the meanwhile: https://github.com/FNNDSC/ami/issues/125

Please let me know if that fixes it!

**Comment by meawoppl** [comment]
I will take a look at that this pm

**Comment by meawoppl** [comment]
This sort of works. If there are multiple volume renders in the scene they interact oddly, along the lines of a poorly sorted painters algorithm.

**Comment by NicolasRannou** [comment]
Yes, volume render multiple volumes at the same time can be tricky and is not supported yet. Are you interested into looking into it?

Closing for now, please re-open if the original issue is not resolved, or open an new issue to discuss further multiple volume renderings!
