### ISSUE TITLE
[build] Use GitHub pages for deployment

### ISSUE THREAD

**Issue by YoneMoreno** [FNNDSC/ami#240]
**Hello and thank you for your time. I would like to use this library to create a web application. In fact I am currently trying to get it deployed in a GitHub Page, in a github.io repository. The point is that I am getting the error:** 

`SyntaxError: import declarations may only appear at top level of a module`

When I try for example to use the viewers_upload example.

The problem is further described here:
https://stackoverflow.com/questions/48367328/how-can-i-use-babel-to-transpile-web-source-code-and-be-able-to-deploy-code-on-a

The github link is:
https://atlasulpgc.github.io/#viewers_upload

Could you help me please?

Thank you.

**Comment by NicolasRannou** [comment]
Answered on SO
