### ISSUE TITLE
[Question] How to retrieve segment's position and convert it to window's coordinates?

### ISSUE THREAD

**Issue by YoneMoreno** [FNNDSC/ami#241]
**Hello and thank you for reading me!**

_I would like to create a function to detect if you have pressed in a image's segment, to be able to display a dialog with a message that informs about it._

By myself, and looking for examples in StackOverflow, I have made the basics to detect if you have pressed and where, and by a condition distinguish if you clicked near a segment or not:

`

    function onWindowClick(event) {
        if (event.clientX > 200 && event.clientX < 300) {
            alert('You have clicked: ' + event.clientX + " " + event.clientY + ' on the segment');
        } else {
            alert('You have clicked: ' + event.clientX + " " + event.clientY + ' out of the segment');
        }
`

The issue is: what data/position/resource do I have to be able to compare the current clicked position and assert that you clicked in or out?

Well, by myself I have examined the data structure, and it looks like there are two options. First, we could use the frame's position, which looks like it represent the segmentation's spatial position, and it looks like: 

Where clicked pos is: 277 294 and **_imagePosition** from data structure is: -201 -59

Also, another alternative is the stack's origin: 

Here the clicked pos is: 278 301 and the **origin** is: -201 -59

So then it looks like whether I choose _imagePosition or origin I would need to do some conversion.

I do have studied that are used an ijk and lps coordinate systems, and in the lessons and examples is common to see a matrix which is updated to convert between them.

**Do you have any suggestions or help? Thank you!**

StackOverflow thread: https://stackoverflow.com/questions/48429241/how-could-we-associate-a-medical-images-segment-position-to-the-clicks-event

**Comment by NicolasRannou** [comment]
Answered on stackoverflow
