### ISSUE TITLE
[Question] Could you help me with this issue: How to deploy a multi javascript files application?

### ISSUE THREAD

**Issue by YoneMoreno** [FNNDSC/ami#243]
**_Hello, thank you for taking time and reading me._**

I am trying to deploy to GitHub pages, and currently I am using Node and WebPack.

I do not know why it says:

_ReferenceError: require is not defined_

When I try to navigate to the page that I have just deployed.

The line being affected is:

_import setCamera from './camera';_

I have read that **require()** is not an implemented function in client browsers: Client on node: [https://stackoverflow.com/questions/19059580/client-on-node-uncaught-referenceerror-require-is-not-defined/19059825](url)

So then I have tried to bundle and minify the JS files, however something I can not explain happens. The pages where I have only one js are correctly minified and the file is called: fileName.js and spaces are deleted and variables are uglified.

However in the page I am doing which I have separated into different js files, those are being bundled with requires such as:

_var _cameras = require('base/cameras/cameras.orthographic');_

**_Is there any way to be able to write different JS files and deploy it in a way that the browser could read it,I mean without using require?_**

The reason why I am confused is because in local with the Node server it works well, however in the remote GitHub pages it does not.

**Thank you for reading me!**

The topic in stackoverflow: https://stackoverflow.com/questions/48420158/deploy-a-web-application-referenceerror-require-is-not-defined

**Comment by NicolasRannou** [comment]
In order to deploy code, you first need to compile it with `yarn dist:examples` will compile all examples into `/dist` directory.

You may want to dig into it at: https://github.com/FNNDSC/ami/blob/dev/package.json#L54
