### ISSUE TITLE
[Feature] Support 'RGB', 'YBR_RCT', 'YBR_ICT', 'YBR_FULL_422' DICOM images

### ISSUE THREAD

**Issue by JSibir** [FNNDSC/ami#247]
When loading this file:
https://drive.google.com/file/d/1XDWFX1BG0WHosSmfNL1gsCqVJjj0YTuT/view?usp=sharing
in this example:
https://fnndsc.github.io/ami/#viewers_upload
we got in console: Error: photometric interpolation not supported: YBR_FULL_422

However, Cornerstone (https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html) opens it without any problems.

I had same problem with single frame US and non US DICOMs

Tried in AMI 0.0.22 and 0.0.23dev

**Comment by NicolasRannou** [comment]
Thanks for opening the bug - all issues are related to `YBR_FULL_422`?

`YBR_FULL_422` seems to behave the same way as RGB so it may just be a matter of adding it there: https://github.com/FNNDSC/ami/blob/dev/src/parsers/parsers.dicom.js#L886-L892

```
    if (
      (photometricInterpretation === 'RGB' || 
       photometricInterpretation === 'YBR_FULL_422') &&
        planarConfiguration === 0) {
...
    } else if (
      (photometricInterpretation === 'RGB' || 
        photometricInterpretation === 'YBR_FULL_422') &&
        planarConfiguration === 1) {
...
```

Would you have some time to give it a shot and submit a PR by any chance?

Thanks!

Ref: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/convertColorSpace.js

**Comment by JSibir** [comment]
Changes from the second post fix the problem.
Tested on several DICOM images (single frame and multi frame US), everything works fine.

**Comment by JSibir** [comment]
It will be great to add all photometricInterpretation from Cornerstone at once
`['RGB', 'YBR_RCT', 'YBR_ICT', 'YBR_FULL_422'].indexOf(photometricInterpretation) !== -1`
