### ISSUE TITLE
Performance getting slow when too many slices loaded

### ISSUE THREAD

**Issue by tymiao1220** [FNNDSC/ami#248]
I am using AMI for dicom stack visualization. When few slices are loaded (40 slices), it performs pretty smooth and well and FPS will keep stable around 60, whereas if I load too many (300 slices), the whole page will be caton, and FPS will keep in very low around 3.

So I am wondering what causes that issue? Is there a good way to address that? Because in my case multiple slices might be necessary.

Thank you for this nice library!

**Comment by NicolasRannou** [comment]
Do you have a live demo by any chace?

You load all slices in the same renderer?

**Comment by tymiao1220** [comment]
I push my src code and example data on github, feel free to pull and take a look. Appreciated your help!

[src code](https://github.com/tymiao1220/AMi_performance_test.git)
