### ISSUE TITLE
[feature] Thumbnails image from frame

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ami#25]
Add a method to get well formatted data to display thumbnails easily.

**Comment by JSibir** [comment]
I am very interested in implementation of this feature.

Maybe [Cornersote](https://github.com/cornerstonejs/cornerstone) already have something what can be used to generate frame thumb?

Also, I found models/stack/_packTo8Bits method. Can it be simplified? Or I am on the wrong way?

Any suggestions for what to begin with?

**Comment by NicolasRannou** [comment]
Minutes from Slack:
```
Nicolas Rannou My current idea for the preview was to `createObjectURL` from the frame data so we can then just pass it as an attribute to a `<img src=<the image>/>`

we have have to convert `frame data` to `blob` to `object url`
[9:51 AM]
Evgenii Sibirtcev I try to draw it on canvas. Without conversion it poorly works for each 4th image (most CT). So I need conversion algorithm.
[9:52 AM]
Nicolas Rannou Yes I would avoid canvas if possible and try to use <img> to display the image
[9:52 AM]
Evgenii Sibirtcev Your approach is better, but algorithm may be more complicated.
Do have have any thoughts where to get this algorithm?
[2:02 PM]
Nicolas Rannou Could help: https://gist.github.com/candycode/f18ae1767b2b0aba568e
Not quite sure what is the syntax to provide width/height to the blob, and which type it should be
[2:11 PM]
Nicolas Rannou maybe just create a stackoverflow question about converting “array buffer” to “blob” to “object url” to be displayed in an image. Can not be too hard
```

**Comment by NicolasRannou** [comment]
Did you have a chance to look into it?

**Comment by JSibir** [comment]
I'll try to look on it on this week.

**Comment by JSibir** [comment]
There are 2 mathods to use <img>:
1) convert frame.pixelData to bmp or png, then pass it to src
`img.src =  'data:image/png;base64,' + myBase64EncodedData;`
2) draw frame.pixelData on canvas, then pass it to src
`img.src = canvas.toDataURL();`

Moreover frame.pixelData isn't a Uint8Array so it must be converted to use any of method described above.

**Comment by NicolasRannou** [comment]
Sounds good

> frame.pixelData isn't a Uint8Array

Yes, that's maybe a bummer but it's OK as it is a one-time operation.

**Comment by JSibir** [comment]
Done in [PR 261](https://github.com/FNNDSC/ami/pull/261)
