### ISSUE TITLE
volume rendering problem

### ISSUE THREAD

**Issue by loveunCG** [FNNDSC/ami#257]
Help me : ami.js volume rendering problem
Now I am using vr_singpass of ami.js to perform volume rendering of Dicom images.
However, volume rendering does not work for some dicom images.
Is this my fault or the problem of ami.js?
Ask for help. Thank you.

**Comment by NicolasRannou** [comment]
Can you please share some data with us?

Can you visualize the data at: https://fnndsc.github.io/ami/#viewers_upload

**Comment by loveunCG** [comment]
Hi Dear
Thank you for your reply.
I have upload my dicom files
I have already show that visualize view.
How can i share that this file .
please contact me
best regards

**Comment by NicolasRannou** [comment]
> I have already show that visualize view.
Not sure what you mean, does it work?

> How can I share that this file
You can share 1 ANONYMIZED data directly in here or in a zip file, with GDrive, etc.

**Comment by loveunCG** [comment]
I have directly attached that file
hello
now in My custome project still yet that file
i dont know why.
thank you

**Comment by loveunCG** [comment]
now there is problem in volume rendering using vr_singpass

**Comment by loveunCG** [comment]
I cannt get volume redering view from that file

**Comment by NicolasRannou** [comment]
Oops I missed it sorry

**Comment by loveunCG** [comment]
there is no error on console
there is many file like that.
this is my screenshot on local workstation.

![g 7t yf fv idvueqiiy2f](https://user-images.githubusercontent.com/25122195/37289931-55ab0820-264e-11e8-8a9f-d52ee1924da4.png)

**Comment by xieyoung** [comment]
I also encountered such a problem.
Such a Dicom images is performed volume rendering in a viewer such as Radiant Dicom Viewer.
Thank you.

**Comment by daron1337** [comment]
you need to play w/ parameters such as ww/wc and shading options, if active. But it works.
<img width="642" alt="screen shot 2018-03-21 at 10 22 42" src="https://user-images.githubusercontent.com/572819/37702126-e2a7b134-2cf1-11e8-87c5-0313128cbc8a.png">
<img width="527" alt="screen shot 2018-03-21 at 10 24 35" src="https://user-images.githubusercontent.com/572819/37702193-115cb254-2cf2-11e8-8056-b55f28b6e2a5.png">

**Comment by bayesianio** [comment]
Hi @loveunCG 
Did you resolve this issue? 
I have a similar problem, can you share the code snippet? 

Thanks,

**Comment by NicolasRannou** [comment]
That should all be working - can you share a live demo? Also make sure to use the latest version from Github!

**Comment by NicolasRannou** [comment]
@bayesianio is it working for you now?
