### ISSUE TITLE
The demo singlepass is error.

### ISSUE THREAD

**Issue by gjun-neusoft** [FNNDSC/ami#266]
Demo provides a lot of resources link has expired, I want to study singlepass, but the demo error. The following screenshot of console

**Comment by gjun-neusoft** [comment]
![error_pic](https://user-images.githubusercontent.com/7803188/38127386-835d2e8c-3428-11e8-9817-e7896eeac434.jpg)

**Comment by gjun-neusoft** [comment]
![error_pic](https://user-images.githubusercontent.com/7803188/38129529-0212f582-3432-11e8-83b3-82317bb475d7.jpg)
![Uploading error_pic.jpg…]()

**Comment by JSibir** [comment]
Everything works perfect on my PC.

If you still have this problem, it is a network or internet provider issue.

**Comment by NicolasRannou** [comment]
It may have happened if `cdn.rawgit` was down. Otherwise, the URL may not be accessible from your location (i.e. China, Russia, etc.) and you may want to use a VPN.
