### ISSUE TITLE
JPEG2000 decoder can't parse multi tile files

### ISSUE THREAD

**Issue by JSibir** [FNNDSC/ami#273]
### Description
[Unsupported file](https://github.com/FNNDSC/ami/files/1902582/JPEG2000.decoder.returned.a.tileCount.more.then.1.zip)
Get error in console when trying to open it:
> Error: JPEG2000 decoder returned a tileCount of ${tileCount}, when 1 is expected

File has several tiles, so parser should be corrected to support such files.
One solution is to merge tiles obtained from https://github.com/OHIF/image-JPEG2000.

#### Steps to Reproduce
[AMI](https://fnndsc.github.io/ami/#viewers_upload) can't open it
[cornerstoneWADOImageLoader](https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/) can't open it

#### Expected Results
[DicomLibrary](https://www.dicomlibrary.com/) opens it perfectly

### Versions
- AMI: v0.0.23dev

**Comment by JSibir** [comment]
[cornerstoneWADOImageLoader](https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/dicomfile/) now return another error in console:
> Uncaught RangeError: Source is too large at Uint8Array.set ()
> cornerstoneWADOImageLoaderCodecs.js:2807

**Comment by NicolasRannou** [comment]
Please open an issue on  `cornerstonejs/cornerstoneWADOImageLoader` Github repository, that will be the bestway to address it.

**Comment by JSibir** [comment]
It was opened 5 hours ago:
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/201

**Comment by JSibir** [comment]
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/201

**Comment by JSibir** [comment]
Solved by using modified version of [OpenJPEG library](https://github.com/joedrago/openjpeg) in [this](https://github.com/FNNDSC/ami/pull/319) PR
