### ISSUE TITLE
Read an DICOM files, render 3d, edit the 3d and export a tray that calculate automatic the size. Thas is possible, with AMI? 

### ISSUE THREAD

**Issue by Chyper00** [FNNDSC/ami#281]
I need to read multiple DICOM files, which comes from a mouth, so I need to render it in 3D, then the Dentist will do edits of the model, and put punctuation marks, the result of this will be a 3D mold for perforations, I have a little knowledge in JS, but I need help, I do not know much about the AMI project. In fact it's my 1st project.

**Comment by NicolasRannou** [comment]
Welcome! That is possible but pretty advanced I'd say :)

Can you tell more about this project? Do you have a desktop application/videos that describe what you are aiming for?

**Comment by NicolasRannou** [comment]
Interesting - yes that is definitely possible but for sure not easy or quick :)

FYI @daron1337

**Comment by NicolasRannou** [comment]
Please open another issue if you have a specific question!
