### ISSUE TITLE
MHD pixelType is not set ?

### ISSUE THREAD

**Issue by PtiLuky** [FNNDSC/ami#291]
I was working with a mdh with float value and everything was black... ( 0 <= values < 1).

It turns out pixelType is always "0".

I think we need in parser.mhd.js (https://github.com/FNNDSC/ami/blob/dev/src/parsers/parsers.mhd.js), around line 77 : 
```js
    let type = 0;
    if (this._header.ElementType === 'MET_UFLOAT' ||
        this._header.ElementType === 'MET_FLOAT') {
      type = 1;
    }
    return type;
```

**Comment by NicolasRannou** [comment]
Do you know which is you element type?

**Comment by PtiLuky** [comment]
My file is a 'MET_FLOAT' .mhd (min = 0, max = 0.4...).
There are values in _frame but after the call to "_packTo8Bits" I have only 0's in _rawData. 
I checked pixelType it's always 0 (while changing it resolves the problem).

**Comment by NicolasRannou** [comment]
Does 
>  let type = 0;
    if (this._header.ElementType === 'MET_UFLOAT' ||
        this._header.ElementType === 'MET_FLOAT') {
      type = 1;
    }

solve it?

**Comment by PtiLuky** [comment]
In my case yes
(but I'm not sure other cases are covered or it didn't break anything else)

**Comment by NicolasRannou** [comment]
I think that makes sense, please just submit a PR when you have a chance
