### ISSUE TITLE
Dicom files rendered incorrectly

### ISSUE THREAD

**Issue by eduardor2k** [FNNDSC/ami#297]
Hi to everyone, it appears dicom files are rendered incorrectly.

https://fnndsc.github.io/ami/#viewers_compare

![image](https://user-images.githubusercontent.com/318278/41414493-7b3cdb18-6fe6-11e8-921b-5fdbbfa8910e.png)

under mricron

![image](https://user-images.githubusercontent.com/318278/41414625-dc066b94-6fe6-11e8-9ffd-996208c5e143.png)

The pixels colored in violet, should be white.

This bug is visible in Firefox and Chrome under ubuntu.

**Comment by NicolasRannou** [comment]
Hi @eduardor2k , is this example not working on your machine? https://fnndsc.github.io/ami/#viewers_compare

Or is it a different dataset?

**Comment by PtiLuky** [comment]
@NicolasRannou this example shows the same result on my computer aswell.

I saw something like that, 
For any stack not in a StackHelper (as Layer1 here) : 
Looks like threshold and offset problem caused by negatives values.
if values are -1000 to 3000, threshold will be set as [-1000, 3000], but real values will be translated to [0 - 4000] to render properly (but with the [-1000, 3000] threshold, >3000 values won't be rendered), showing the background (violet).
Setting threshold with the offset with negative values resolved the problem for stack.

([here](https://github.com/FNNDSC/ami/blob/dev/examples/viewers_compare/viewers_compare.js#L384))
```
uniformsLayer1.uLowerUpperThreshold.value = [...stack2.minMax];
```
Changed to 
```
let offset = Math.min(0, stck.minMax[0]);
uniformsLayer.uLowerUpperThreshold.value = [stack.minMax[0] + offset, stack.minMax[1] + offset];
```

**Comment by NicolasRannou** [comment]
Good catch. Also slope/intercept should be applied to the threshold:
Bug: https://github.com/FNNDSC/ami/blob/dev/src/helpers/helpers.slice.js#L384-L396
```
   // adding thresholding
    if (this._upperThreshold === null) {
      this._upperThreshold = this._stack._minMax[1];
    }

    if (this._lowerThreshold === null) {
      this._lowerThreshold = this._stack._minMax[0];
    }
```

should be:
```
   // adding thresholding
    if (this._upperThreshold === null) {
      this._upperThreshold = this._rescaleIntercept + this._rescaleSlope * this._stack._minMax[1];
    }

    if (this._lowerThreshold === null) {
      this._lowerThreshold = this._rescaleIntercept + this._rescaleSlope * this._stack._minMax[0];
    }
```

@PtiLuky can you try to set upper/lower threshold as using rescale slope instead of offset?
that should be the way to go...

**Comment by PtiLuky** [comment]
@NicolasRannou 
I'm not sure about that, slope/intercept looks already applied in threshold (in _minMax ) : 
https://github.com/FNNDSC/ami/blob/dev/src/models/models.stack.js#L253-L260

**Comment by NicolasRannou** [comment]
you are correct @PtiLuky ! so the issue is just in the example then?

**Comment by PtiLuky** [comment]
I had to do the offset "trick" when I set shader data uniforms by myself (ie not using StackHelper). The stackhelper does that [here](https://github.com/FNNDSC/ami/blob/dev/src/helpers/helpers.slice.js#L412-L415).

What I can't figure out about this example here is that I see the problem with this online version, but when I run from my computer it seems perfectly fine...

**Comment by NicolasRannou** [comment]
@eduardor2k does the current version work for you?

**Comment by eduardor2k** [comment]
@NicolasRannou it seems everything is rendering correctly.
