### ISSUE TITLE
HelpersSlice opacity property missing [Duplicated]

### ISSUE THREAD

**Issue by eduardor2k** [FNNDSC/ami#304]
It seems that all the properties of the viewer are contained inside the "HelpersSlice", but one option that is mising is to be able to change the slice opacity.

**Comment by PtiLuky** [comment]
For the moment I don't think you can change the opacity of a slice.

Is the issue the same as this suggestion : https://github.com/FNNDSC/ami/issues/290 ?

**Comment by eduardor2k** [comment]
@PtiLuky yes, it's the same
