### ISSUE TITLE
Loading NIFTI files takes a lot of time to process, DICOM the same but feels faster

### ISSUE THREAD

**Issue by eduardor2k** [FNNDSC/ami#315]
Loader should behave differently if the user is trying to load 100 dicom files or 1 big nifty file, i suggest adding in the update method the number of files procesed and the total files to process.

**Comment by JSibir** [comment]
This is already partly implemented in Progress Bar Helper

**Comment by NicolasRannou** [comment]
So there are 2 parts of this problem: loading the data from the server and displaying it on the screen. Right now, the loaders/examples wait for all the data to have arrived before creating the stack helper from it but ideally we should be able to add data on the fly to the stack helper - somehow...

**Comment by eduardor2k** [comment]
It seems the browser stays a lot of time converting image data from 32 bits to 8bits (ModelStack._packTo8Bits), maybe it should be better to generate an empty texture, and convert asynchronously all the frames

**Comment by eduardor2k** [comment]
the problem is that _packTo8Bits freezes the browser, it has to process 8.000.000 items (in my case).

I improved a little bit the browser response, returning an empty texture an updating the data by chunks, it allows the browser to be responsive.

**Comment by eduardor2k** [comment]
The match function:

let bitStringArray = bitString.match(/.{1,8}/g);

is only separating 32 bits into 4x8bit chunks...

**Comment by eduardor2k** [comment]
It seems my solution is not faster at all:

https://jsperf.com/splitting-strings-with-split-vs-regexp

Closing
