### ISSUE TITLE
Parse URL

### ISSUE THREAD

**Issue by eduardor2k** [FNNDSC/ami#321]
Hi! eventhough MDN says that the second parameter for URL (the base url, defaults to ""), it's not a valid value. :unamused:

https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

You can try in the console of your browser:

new URL('http://www.google.com/myfile.zip','') // you will get "TypeError: Failed to construct 'URL': Invalid base URL" on chrome and "TypeError:  is not a valid URL." on FF.

From the documentation, it seems that the base url needs to be always a URL.

new URL('http://www.google.com/myfile.zip','http://www.google.com') => http://www.google.com/myfile.zip
new URL('/myfile.zip','http://www.google.com') => http://www.google.com/myfile.zip

new URL('http://www.google.com/myfile.zip','http://www.otherdomain.com') => http://www.google.com/myfile.zip
new URL('/myfile.zip','http://www.otherdomain.com') => http://www.otherdomain.com/myfile.zip

@JSibir could you try this change in your code:

      -const absUrlRe = /^(?:[a-z]+:)?\/\//i,
      -parsedUrl = new URL(url, absUrlRe.test(url) ? '' : location.origin),
      parsedUrl = new URL(url, location.origin),
      data = {
        filename: parsedUrl.searchParams.get('filename'),
        extension: '',
        pathname: parsedUrl.pathname,
        query: parsedUrl.search,
      };

**Comment by JSibir** [comment]
I done it in slightly another way: https://github.com/FNNDSC/ami/pull/322

**Comment by eduardor2k** [comment]
@JSibir Thanks for the push request!

**Comment by NicolasRannou** [comment]
Can we close it now?

**Comment by eduardor2k** [comment]
Closed
