### ISSUE TITLE
Using AMI as a module (in webpack) no longer works.

### ISSUE THREAD

**Issue by Kingdutch** [FNNDSC/ami#334]
### Description
#110 ensured that AMI was build as a CJS module by babel before being published to NPM. This ensured that an `import` properly resolved all dependencies as well.

#195 Migrated to Webpack which removed this from the build system. 

Currently AMI only outputs a browser ready bundle which requires a global THREE variable to be present. When using Webpack to bundle the application this means that ThreeJS is not automatically added as dependency and a shim is required. It would be great if we could reinstate the changes made in #110 that were removed in #195 so that THREE is properly imported and detected by webpack.

#### Live Demo
I do not currently have a live demo of this unfortunately.

#### Steps to Reproduce

1. Set up a basic webpack project (Webpack 4 with no configuration should work). 
2. In your main source file use `import * as AMI from 'ami.js'
3. Call `new AMI.OrthographicCamera`

Note that with the build steps that were introduced in #110 I believe there was no need to use `import * as`.

#### Expected Results
The code works without errors.

#### Actual Results
The console shows an error "THREE not defined".

### Browsers Affected
- [x] All
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- AMI: v0.0.22
- THREEJS: v0.94.0

**Comment by NicolasRannou** [comment]
@Kingdutch, you should now use the factories to use AMI in you Qebpack project (I currently use AMI in an application based on create-react-app).

```
import * as THREE from 'three';
import {stackHelperFactory} from 'ami.js';

const StackHelper = stackHelperFactory(THREE);
const sh = StackHelper();
```

**Comment by Kingdutch** [comment]
Aah I see : )

Is there a way to add 'next' as a dist-tag? Currently I can only install 0.0.22 through Yarn (which doesn't have the factories yet) and I can't say `yarn add ami.js@next` because Yarn has no knowledge of the dev or 0.0.23-dev version.

I can install from the git repo itself but that's a lot slower and more cumbersome to keep up to date :)

**Comment by NicolasRannou** [comment]
@Kingdutch yes a @next would be ideal, do you have some experience on setting that up so that after each new PRs is merged, Travis publishes a new NPM package?

**Comment by NicolasRannou** [comment]
that would be awesome! thanks!

**Comment by Kingdutch** [comment]
Sorry, I should've probably prefixed "Could" with a pronoun. Unfortunately I don't have the time available to figure this out myself at this moment.

**Comment by xgui3783** [comment]
I have played around with another unrelated project requiring `THREE` as a global variable. The said project I was using `webpack` and ES6 import syntax. This may or may not suit your need, but I circumvented the problem with:

```
import * as THREE from 'three'
window['THREE'] = THREE
import 'three/examples/js/controls/TrackballControls'
```

**Comment by NicolasRannou** [comment]
@xgui3783 we no longer require `threejs` as a global variable, using the factory pattern:

```

import {stackHelperFactory} from 'ami.js';
import * from 'THREE';

const StackHelper = stackHelperFactory(THREE);
const sh = new StackHelper();
```

**Comment by Kingdutch** [comment]
@NicolasRannou I think this can be closed, unless some documentation somewhere still needs to be updated? :)

**Comment by NicolasRannou** [comment]
@Kingdutch you are right, auto-deployement is a different problem!

**Comment by msimonc** [comment]
This worked on our Electron project:

yarn add ami.js@0.32.0
