### ISSUE TITLE
Remove lessons from code base

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ami#349]
* Remove lessons files
* Adjust build script
* List lessons / js fiddles in the wiki

**Comment by theblindprophet** [comment]
Working on it.

**Comment by NicolasRannou** [comment]
Thanks! So the lesson should just be public fiddles from now on, and we can reference them in a wiki!

**Comment by theblindprophet** [comment]
@NicolasRannou So just completely ripping out the `lessons` folder and making sure that `npm run build:ami:prod` works?

**Comment by NicolasRannou** [comment]
We may also have to create the JSFiddles for each lesson? (not sure, it is now loading data from Github)

We should also clean up the build scripts to remove all the mentions to lessons and only keep examples.

Does it make sense?

**Comment by theblindprophet** [comment]
Yeah I'll get a PR up first removing `lessons` from the build and elsewhere. So lessons won't be accessible from the website anymore? Just the WIKI?

**Comment by NicolasRannou** [comment]
The lessons will not be part of the repo anymore, it will be accessible from Wiki/Readme and directly hosted on JSFiddle!

**Comment by NicolasRannou** [comment]
Closing - after exploring options, `codesandbox` lets us load lessons without requiring any special formatting. Keeping lessons in code base without a dedicated build script.

We just need to adjust the code from the lessons directory such as https://github.com/FNNDSC/ami/tree/dev/lessons/00

**Comment by NicolasRannou** [comment]
Ref of new issue: https://github.com/FNNDSC/ami/issues/358
