### ISSUE TITLE
Create cool logo for WebGL Medical software AMI

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ami#350]
Ideally SVG and PNG versions, different color schemes

**Comment by tibetegya** [comment]
Hey @NicolasRannou I think This is a task I can take on. I will create a logo and share it in a next 24 hours

**Comment by NicolasRannou** [comment]
That'd be awesome, current "logo" is supposed to represent a "paper snake" (medical reference)  -

**Comment by NicolasRannou** [comment]
![78ade038-f90c-11e6-8208-4fcade5f3832](https://user-images.githubusercontent.com/214063/46335581-31206c00-c628-11e8-9937-91e1e2aa3f85.png)

**Comment by NicolasRannou** [comment]
some tests:

![0001-ami-logo 04](https://user-images.githubusercontent.com/214063/46335615-4b5a4a00-c628-11e8-92f8-09e9c0aa1595.png)

**Comment by NicolasRannou** [comment]
<img width="345" alt="screenshot 2018-10-02 at 09 51 03" src="https://user-images.githubusercontent.com/214063/46335732-b4da5880-c628-11e8-8ac1-1d5d3c96f416.png">

**Comment by NicolasRannou** [comment]
https://www.google.es/search?q=gitlab+logo&tbm=isch&source=iu&ictx=1&fir=cn4FkwhwqKrWNM%253A%252C_O7KY3qKe2M2ZM%252C_&usg=AI4_-kS5bWe5dkP1n1eiNFfU35yCzER0TA&sa=X&ved=2ahUKEwj36f6Mo-fdAhUksqQKHXD-BaMQ9QEwAnoECAYQCA#imgrc=cn4FkwhwqKrWNM:

**Comment by NicolasRannou** [comment]
Lot of options, looking forward to see what you come up with

**Comment by NicolasRannou** [comment]
Closed by https://github.com/FNNDSC/ami/pull/353
