### ISSUE TITLE
Lesson 01: Visualize 3D does not work.

### ISSUE THREAD

**Issue by tommychang1983** [FNNDSC/ami#38]
Test for both Chrome Version 48, 64-bit and Safari.
The fiddle example could not display anything. Please take a look.

**Comment by NicolasRannou** [comment]
Hi @tommychang1983, thanks for letting us know -

I could reproduce on Safari but not with Chrome. (chrome 50 - 64bits)

Can you please confirm that none of the following JS Fiddle work but that the other example work?
It seems to be a JS Fiddle related issue.

Lessons (should not work)
No WebGL: http://jsfiddle.net/gh/get/library/pure/fnndsc/ami/tree/master/lessons/00#run
WebGL: http://jsfiddle.net/gh/get/library/pure/fnndsc/ami/tree/master/lessons/03#run

Examples (should work)
http://fnndsc.github.io/ami/#loader_dicoms

Thanks

**Comment by NicolasRannou** [comment]
@tommychang1983 it should be working now, the issue was that I was using "let" instead of "var" in the demo.
Please let me know if that doesn't fix it or if you have any other question/feature request/etc.

**Comment by tommychang1983** [comment]
Hi Nicolas, 
Sorry for my late response. 
It works now in my chrome! thanks
