### ISSUE TITLE
How to start the AMI 

### ISSUE THREAD

**Issue by amir201808** [FNNDSC/ami#382]
![Screenshot_8](https://user-images.githubusercontent.com/42467630/57853176-aaa94b00-7802-11e9-9c1a-84faaab41306.png)
Hello Friends,

I have clone this repo and ran all the commands listed with ran the yarn commands as written in steps. Upload file is not working the way it is working in live.
Please guide me how to proceed.

Live Link - https://fnndsc.github.io/ami/#viewers_upload 

Thank you

**Comment by colinlaney** [comment]
I guess you started simple Python server instead of compiling Typescript code. To do that just run
```bash
$> yarn install
$> yarn example viewers_upload
```
See `examples` directory to list all available.

**Comment by amir201808** [comment]
Hello Colinlaney,

It's done seperately. When I tried to install the package as the whole it threw error. When I tried using codes seperately It worked.
I tried using the lesson 03 code seperately and it worked. I can now upload the .nii and .dcm file individually.

Thanks,
Amir
