### ISSUE TITLE
Potential windows bug

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ami#39]
examples/viewers_dicom2D/index.html three.min.js:631 THREE.WebGLRenderer 75 models.stack.js:235 do not know how to order the frames... – Hemanth Anakapalle 10 hours ago
  	
 		
three.min.js:704 THREE.WebGLProgram: shader error: 0 gl.VALIDATE_STATUS false gl.getProgramInfoLog C:\fakepath(167,37-79): error X4002: indefinite logarithm Warning: D3D shader compilation failed with default flags. (ps_3_0) Retrying with avoid flow control C:\fakepath(167,37-79): error X4002: indefinite logarithm Warning: D3D shader compilation failed with avoid flow control flags. (ps_3_0) Retrying with prefer flow control C:\fakepath(167,37-79): error X4002: indefinite logarithm – Hemanth Anakapalle 10 hours ago
  	
 		
Warning: D3D shader compilation failed with prefer flow control flags. (ps_3_0) Failed to create D3D shaders. – Hemanth Anakapalle 10 hours ago
  	
 		
WebGL: INVALID_OPERATION: useProgram: program not valid three.min.js:671 WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use 254three.min.js:600 WebGL: INVALID_OPERATION: useProgram: program not valid three.min.js:600 WebGL: too many errors, no more errors will be reported to the console for this context. – Hemanth Anakapalle 10 hours ago
  	
 		
I am seeing all these errors over browser console. I am trying this over windows, Is it fine ? –

**Comment by HemanthAnakapalle** [comment]
**OS** : Windows 7 Professional
**System Type** : 64-bit

**Chrome Version** : Version 50.0.2661.102 m
(Google Chrome is up to date.)

Attached **snapshots of the issue**, **console logs** and also rest available information (see if it helps to debug).

It is an critical issue, please prioritize this, Thanks.
![dicom_viewer_issue](https://cloud.githubusercontent.com/assets/19338963/15272179/e5e30446-1a8a-11e6-9ddb-23913624ced7.JPG)
![chrome_console_logs](https://cloud.githubusercontent.com/assets/19338963/15272180/ed6b8c4c-1a8a-11e6-9d7d-7bd794f83f08.JPG)
![info_1](https://cloud.githubusercontent.com/assets/19338963/15272181/f39efe1e-1a8a-11e6-9a40-ec7da8ad3023.JPG)
![info_2](https://cloud.githubusercontent.com/assets/19338963/15272183/fa709cb6-1a8a-11e6-84c7-f672a4c46bb8.JPG)
![info_3](https://cloud.githubusercontent.com/assets/19338963/15272184/fd2faff0-1a8a-11e6-9412-a25c3a334bd6.JPG)

**Comment by HemanthAnakapalle** [comment]
Note : It is working fine on my friend's laptop. His OS is windows 10.

Chrome version is same on our both laptops.

**Comment by NicolasRannou** [comment]
Hmm I tried on a windows 7 VM and Internet Explorer and it worked fine.

Does the following work on your machine?
http://jsfiddle.net/gh/get/library/pure/fnndsc/ami/tree/master/lessons/03#run

Also, can you try it in an "incognito" tab to see if it could be a cache issue?

Thanks

**Comment by HemanthAnakapalle** [comment]
Tried both Nicolas .... still same, not working.

**Comment by NicolasRannou** [comment]
OK - and in the console when it writes down the error, can you click on it somehow to see which line of the shaders is the problem?

**Comment by NicolasRannou** [comment]
Are your graphic card drivers up to date too?

**Comment by NicolasRannou** [comment]
Can you please try this one?

http://jsfiddle.net/w1r76rxm/

**Comment by HemanthAnakapalle** [comment]
Drivers I will check.

Tried latest link too, still same.
![1st_link](https://cloud.githubusercontent.com/assets/19338963/15288318/58929b12-1b87-11e6-9609-77623c7f78f9.JPG)
![2nd_link](https://cloud.githubusercontent.com/assets/19338963/15288322/69323856-1b87-11e6-93d5-1be1f8f6a942.JPG)

**Comment by NicolasRannou** [comment]
OK - If you click on the link for (anonymous function) (index):159 in the error message, does it point you to the fragment shader code that can not be compiled?

**Comment by HemanthAnakapalle** [comment]
Yes ... it is pointing to "animate();" statement.

**Comment by NicolasRannou** [comment]
OK :/

I would now make sure the drivers are up to date then.

Does this one work?
http://threejs.org/examples/#webgl_shader_lava

**Comment by HemanthAnakapalle** [comment]
working ... (y)

**Comment by HemanthAnakapalle** [comment]
what is the issue ?

**Comment by NicolasRannou** [comment]
hmmm no idea yet, for some reason your machine can not compile the shaders properly. 

Can you try in internet explorer?

**Comment by HemanthAnakapalle** [comment]
http://threejs.org/examples/#webgl_shader_lava

This is working Nicolas.

**Comment by NicolasRannou** [comment]
yes sorry, I meant try the ami fiddle:
http://jsfiddle.net/w1r76rxm/

**Comment by HemanthAnakapalle** [comment]
Tried on all browsers ... it is not working.

**Comment by NicolasRannou** [comment]
It would be really useful if we could know what part of the shader it is referring to:
![screen shot 2016-05-16 at 2 26 43 pm](https://cloud.githubusercontent.com/assets/214063/15289431/62b1518e-1b72-11e6-85e4-acf09ea4c69b.png)

**Comment by HemanthAnakapalle** [comment]
![code](https://cloud.githubusercontent.com/assets/19338963/15289680/6ffde180-1b91-11e6-8e59-7c892ac37a80.JPG)

**Comment by NicolasRannou** [comment]
this one points to the THREE.JS code, is there any way to see the AMI JS shader code that triggered this error?

**Comment by NicolasRannou** [comment]
Can you also try this one: (threejs 76)

http://jsfiddle.net/w1r76rxm/

**Comment by NicolasRannou** [comment]
Can you try this one in an incognito tab?
http://jsfiddle.net/xf12mc2y/

There was an illegal shader declaration which could have created the issue...

**Comment by HemanthAnakapalle** [comment]
Last link is working in incognito tab. But not in normal tab.

**Comment by NicolasRannou** [comment]
Awesome, the issue was the following line of code:
```
int issigned = int(pow(-1., float(bytemeR[0])));
```
that I replaced by:
```
int issigned = 1 - 2 * bytemeR[0];
```

https://github.com/FNNDSC/ami/commit/8d2616647372c6944b2377abdfcb6541ae94f436

I cut a new release and you should be good to go now.

If it only works in "incognito mode", it is because an older version of the library is still in the cache. Reload the page while pressing "shift" and you should be good to go.

Please try to load the dataset you couldn't to make sure it all works now:
https://fnndsc.github.io/ami/examples/viewers_dicom2D/

Thanks!

**Comment by HemanthAnakapalle** [comment]
It works, Good.

Thanks.

**Comment by NicolasRannou** [comment]
Great! thanks for helping to track it down!
