### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by PunkHaz4rd** [FNNDSC/ami#50]
People should be able to install it with bower.

**Comment by NicolasRannou** [comment]
Yes it is not published to bower, however you can just get it from Github with bower:
```
bower install FNNDSC/AMI#master
```

#master is the latest release, you can also target specific tags like.

```
bower install FNNDSC/AMI#v0.0.8"
```

Please re-open if something doesn't work.

Thanks for filling the report!

**Comment by PunkHaz4rd** [comment]
So I have installed it with bower, though I stumble when I try to integrate it with gulp.

I understand the need to use browserify and stuff, but I don't really know how to integrate them in my tasks.

The way it is now, I use bowerFiles(), and in production, there's a bug with ngAnnotate.
How should I include the build of the library in this kind of task : 

    pipes.builtVendorScriptsDev = function() {
        return gulp.src(bowerFiles())
        .pipe(gulp.dest('dist.dev/bower_components'));
    };

Thanks

**Comment by NicolasRannou** [comment]
The easy way is just to use the already browserified version (that still needs to be optimized though...)

Just include `dist/ami.js` in your app then use `AMI` as we do in the lessons.

For instance: http://jsfiddle.net/gh/get/library/pure/fnndsc/ami/tree/master/lessons/01#run
