### ISSUE TITLE
Black Box when exporting to OBJ Format

### ISSUE THREAD

**Issue by Brucewayne01** [FNNDSC/ami#52]
I used the Three.js obj exporter  https://github.com/mrdoob/three.js/blob/master/examples/js/exporters/OBJExporter.js

and this code to download the file `

    var exporter = new THREE.OBJExporter();
    var result = exporter.parse(scene);
        
    var link = document.createElement('a');
    document.body.appendChild(link); 
    save( new Blob( [ result], { type: 'text/plain' } ), 'model.obj' );
    
	function save( blob, filename ) {

		link.href = URL.createObjectURL( blob );
		link.download = filename || 'data.json';
		link.click();

		// URL.revokeObjectURL( url ); breaks Firefox...

	}`
and i get a black box

**Comment by NicolasRannou** [comment]
Does OBJ exporter also exports textures?

Do you havea  fiddle for it?

**Comment by Brucewayne01** [comment]
No OBJ format doesn't export textures

http://jsfiddle.net/bruce_wayne007/76kg713d/2/

If I can't export textures, can I get only the geometry instead of a Cube ?

**Comment by NicolasRannou** [comment]
If by geometry you mean show the edges of the "black box", you could copy the geometry from VR Helper and create a new mesh with it and a new wireframe material.

Closing - Please feel free to re-open if needed.

**Comment by Brucewayne01** [comment]
No , I didn't mean the box, i meant alll the volume rendering in a geometry with all the vertices to export it to an OBJ or STL format.

**Comment by NicolasRannou** [comment]
Do you mean that you want to create a geometry from the raw data, map export each **voxel** to a **vertex** and a **color**?

I did this kind of experiments a while back and it didn't work well at the time.

Generate a surface from raw data is not trivial, maybe you could give marching cubes a try...

**Comment by Brucewayne01** [comment]
Yes, i want to create a geometry from the raw data, but how can i get all voxels, or vertices ?

Can I send you a private message ? I need some clarifications
