### ISSUE TITLE
Why not working on Moto X? My mobile GPU are adreno 330,test viewers_dicom2D it's crash,why? please help me!

### ISSUE THREAD

**Issue by SmithWangCH** [FNNDSC/ami#54]

**Comment by NicolasRannou** [comment]
Hi sorry for the delay I was offline -

Which version of the Moto X do you own (year)? Does any other demo work by any chance?

I had a 2014 Moto X that was not properly working either and it had to do with the custom shaders that were passing an array of textures as a parameter of a function. It didn't like it somehow (https://github.com/FNNDSC/ami/blob/master/src/shaders/shaders.data.frag#L36-L43)

Please give a try to the volume rendering that uses a slightly different shader and we can investigate deeper.
https://fnndsc.github.io/ami/#vr_singlepass_raycasting

Does vanilla THREEJS demo work?(http://threejs.org/examples/#webgl_geometry_colors_lookuptable)

Thanks

**Comment by SmithWangCH** [comment]
Hi thank you for your reply .
My mobile not Moto X 2014,but it has the same GPU(Qualcomm adreno 330) with Moto X 2014.
The following picture is my test result
![dicom_2d](https://cloud.githubusercontent.com/assets/20814935/18223731/5b6456b0-71f3-11e6-86ab-52743a5ee21c.png)
![lookup](https://cloud.githubusercontent.com/assets/20814935/18223732/5b6535ee-71f3-11e6-886d-d93d319d0da8.png)
![raycasting](https://cloud.githubusercontent.com/assets/20814935/18223733/5bbcec9e-71f3-11e6-8968-881493e9707d.png)

**Comment by NicolasRannou** [comment]
If you extend the 1st WebGL error:
"Shader error 0 .. validate status false ... three.min.js:714"

Does it tell you which is the problematic line?

![](https://cloud.githubusercontent.com/assets/20814935/18223731/5b6456b0-71f3-11e6-86ab-52743a5ee21c.png)

**Comment by NicolasRannou** [comment]
Closing for now - waiting for answer.

Will re-open if needed.
