### ISSUE TITLE
Error: Cannot find module 'CommonGL/transforms/transformPoint.glsl'

### ISSUE THREAD

**Issue by YiiGuxing** [FNNDSC/ami#58]
Error: Cannot find module 'CommonGL/transforms/transformPoint.glsl' from '~/ami/src/shaders' while parsing file: ~/ami/src/shaders/shaders.js

**Comment by NicolasRannou** [comment]
When do you get that error?

**Comment by YiiGuxing** [comment]
npm install CommonGL
