### ISSUE TITLE
Clip and Contour

### ISSUE THREAD

**Issue by rwirz** [FNNDSC/ami#63]
Hi,

I saw in different forums you are interested in see the mesh contour in the slice and the solution should be to use shaders.

Using AMI and the last version of three.js, you can clip very well meshes like this:

![untitled](https://cloud.githubusercontent.com/assets/8203181/20443850/51c0b23e-ad94-11e6-8762-368be902f6ec.png)

And there is a very small contour in the slice:

![untitled](https://cloud.githubusercontent.com/assets/8203181/20443901/8a983d34-ad94-11e6-9682-50754099f856.png)

Are you working on it? We could use this feature to do a post processing render to grow the thickness of the contour. It is only an idea.

Are you going to use CLIP from three.js or are you going to use yourself?

If you are going to use the clip from three.js, I can upload an example of this feature with AMI.JS

Thanks

**Comment by NicolasRannou** [comment]
Hi @rwirz,

Yes using the clip from threejs was my plan but I did not have time to work on it yet...

If you can write an example with the post processing that would be very helpful!!!

Thanks!

**Comment by rwirz** [comment]
Using you mesh_nrrd.js, an example with CLIP using Three.js.

https://drive.google.com/open?id=0B24ZHnv6xHO4SU5iYl82OTRpOGc

I am working in the post processing now, but I am new in shaders!

P.D. I can not push, I don't have permissions.

**Comment by NicolasRannou** [comment]
Thanks!!! Looking forward to the post processing!

What you can do is 'fork' AMI and submit pull requests!
https://help.github.com/articles/fork-a-repo/

Cheers

**Comment by NicolasRannou** [comment]
Did you manage to get some progess on that already? :)

**Comment by rwirz** [comment]
I am working on it.

With a clip from Three.js and a shader, I obtain this
![untitled](https://cloud.githubusercontent.com/assets/8203181/20774234/1250499e-b71b-11e6-90ae-f18fce18ee28.png)

But it is not satisfactory since the clip for three.js doesn't give a continuous contour. The input should be different from the clip of Three.js. I am trying new things.

**Comment by NicolasRannou** [comment]
Yes it is a bit tricky - are you using stencil buffers? post processing?
This one might help: https://threejs.org/examples/#webgl_postprocessing_outline

**Comment by rwirz** [comment]
I am using post processing as Three.js uses it. But, we need to choose the right "pipeline".
My actual pipeline is:
Clip in one direction, clip in the another direction (but moving the plane 1 mm), put a orthogonal camera in the clip result and ,with a shader, increase the size of the border. But the solution is not optimal (as you see in the picture)

I saw your example before and checked, but the problem is that the mask that they are using is all the object. It is like if the 3D object is projected in 2D. So, you will see the mask of all mesh, not only in one slice or clipped. You can see this picture for a better understanding. 
![untitled](https://cloud.githubusercontent.com/assets/8203181/20812728/4740749a-b7d8-11e6-9c7b-0b7459ae04c3.png)

The solution should be to create a "label" of the mesh in the slice and obtain the contour. All with shaders.

To obtain the label I was thinking to use the same system than the "Clip with Cap" project.

If someone has recommendations, welcome!

**Comment by NicolasRannou** [comment]
Yes you are right the outline is not the right way to go - I opened an issue in ThreeJS to try to see if that could be added as a feature or if we can get some guidance:
https://github.com/mrdoob/three.js/issues/10269

**Comment by NicolasRannou** [comment]
that seems promising too: https://github.com/daign/clipping-with-caps

**Comment by NicolasRannou** [comment]
very interesting feedback from THREEJS:
https://github.com/mrdoob/three.js/issues/10269#issuecomment-265897708

Basically the idea is to add an option in the THREEJS material so the user can decided the style of the "clipped area" (color, border width, etc.)

Does it sound reasonable to implement it as a ThreeJS new feature? Another great benefit is that we would not need any post processing and performance will be much better!

**Comment by rwirz** [comment]
This is great! I will test it next week! Thanks for your help

**Comment by rwirz** [comment]
Hi,

I found two solutions to create the "cap" (or label in our case) and I would like to share to you to discuss about this.

Both solutions are using the CLIP feature from Three.js.

First Solution (two object/duplicate faces - two materials)
--------------
- It is to duplicate the object (or the faces). So, we have two different materials: One is front side and another is backside. The advantage of this method is that if the object rotate (object rotation, no camera rotation!), shadows works great and work with any camera. The disadvantage is that you need to duplicate the mesh or faces (warning, it is not the same duplicate mesh than faces!).
Here it is an example:
![cap_duplicate](https://cloud.githubusercontent.com/assets/8203181/21647112/993ff11c-d25e-11e6-9481-cf09583e0384.png)
And with the shadow perfect!
![cap_duplicate2](https://cloud.githubusercontent.com/assets/8203181/21647126/a46a189c-d25e-11e6-9424-4532d5beca79.png)

Second Solution (one object - two materials)
--------- 
- Have one object and assign material to the faces. Backfaces will have different material from frontfaces. The face normal respect the orthogonal camera defines backfaces.
The disadvantage is that only works with orthogonal cameras , doesn't work with object rotations (because you are changing the faces normal) and the shadow is not good.. The advantage is that you dont need to duplicate the object/faces.
Here is a example that it is perfect in orthogonal view:
![cap_double](https://cloud.githubusercontent.com/assets/8203181/21647277/34c8e030-d25f-11e6-8e56-271b2297640d.png)
But the shadows and angular view is horrible:
![cap_double2](https://cloud.githubusercontent.com/assets/8203181/21647304/4e9c3386-d25f-11e6-9af8-27bb9c919d7b.png)


I think that for Axial, sagittal and coronal view, the second solution is better. But if you want to draw labels in the 3d view, you need to have the first solution.

What do you think?

Next step is to obtain the contour from this labels.

**Comment by NicolasRannou** [comment]
Very nice @rwirz ! Yes solution 2 sounds more simple but I think we should go for solution 1. The main reason I can think about right now is that it is a generic solution that works in both "2D" and "3D" so we do not have to write a special case for 2D and for 3D. (meaning more code to maintain, different APIs, etc.)

Is solution 1 a lot more code to write? Is it much slower?

I'm very happy to see the progress!

**Comment by rwirz** [comment]
Sorry by the delay, but I have a lot of projects and this is low priority.

The theory is that if you have a clipped mesh and you subtract the front face with the back face, you will have the "cap". The "cap" is in 3D, so you need to save the results and render it again in the general render.

Check my code:
I have two scenes, one is the general and the another one is only the mesh. In the scene with the only mesh, I render it with the front face in transparent and with the backface in one color. The result is added to the general scene. This works great when you have one mesh or when you have more than one mesh that don't collide between them. IF they collide, doesn't work. The solution that I found is to create a scene per each mesh and do it. The code that you have here is for two meshes and it is working great! (to obtain the labels)

To obtain contours I have two strategic that I need to test: using UV in shaders or clone and scale. I will continue working on it.

Here some pictures about the code that I post here. (put this file in the examples of three)
[webgl_clipping.zip](https://github.com/FNNDSC/ami/files/732668/webgl_clipping.zip)
![1](https://cloud.githubusercontent.com/assets/8203181/22337533/cb15385c-e3aa-11e6-9520-637a5d1e8ef1.png)
![2](https://cloud.githubusercontent.com/assets/8203181/22337535/ccc611da-e3aa-11e6-9354-ec1774fa4c48.png)

**Comment by NicolasRannou** [comment]
That looks very promising thank you!

I was thinking recently about an alternative that you might have a good sense on how to tackle:

I was thinking because it is very challenging to draw the contours, the first step could be to draw the whole intersection like you have on the second picture, rather than just the contour.

If we can overlay N intersections of N different meshes with different opacities that would already be VERY useful!

Do you see what I mean?

**Comment by rwirz** [comment]
Draw the contours having the label should be "easy", like the picture 1. We only need to do a second render eliminating the blue color or check the UV as the three.js guy told us. (I need to checked it!, sorry by the time)

The hardest part is to obtain the labels. Check this pictures. The first picture is setting each mesh in different scene and render by separate. The results are awesome
![1n](https://cloud.githubusercontent.com/assets/8203181/22376407/6c284b80-e473-11e6-948c-a1a4d7c5a22d.png)

And works with opacities (here blue has 0.5 opacity):

![3n](https://cloud.githubusercontent.com/assets/8203181/22376538/18b0b7ac-e474-11e6-992d-b6f9bfb9b0f1.png)

However, If we have N meshes, we will have N renderings...maybe the FPS will decrease a lor. (I need to check it too!)

Setting all meshes in the same scene will produce this error:
![2n](https://cloud.githubusercontent.com/assets/8203181/22376461/9fa95b48-e473-11e6-9004-1da0f6f90033.png).

So, my followings steps are: 
1. Test it with around 10 meshes (brain segmentations) and check the FPS
2. Obtain the contours trying first UV (in shaders).
3. Obtain the contours cloning the mesh and scaling it.

The good thing is that we are using the clip feature of three.js. The code is something like this:
- Having one mesh:
   - One copy of the mesh with frontfacing and opacity 0. Activate clip local plane in the material
  -  One copy of the mesh with backfacing and opacity X. Activate clip local plane in the material
  - create one scene with both copies.
  - the frontfacing mesh, added it to the general scene (the scene that the user will see).
  - render the general scene and later render "above" the label scene. This is the render order for two meshes (that each mesh will have its own scene):
             renderer.clear();
	     renderer.render(scene, camera);
	     renderer.clearDepth();
	     renderer.render(sceneClip, camera);
	     renderer.clearDepth();
	     renderer.render(sceneClip2, camera);

**Comment by rwirz** [comment]
Example with brain structures.
All meshes are in one scene because there are not in collision.
![1m](https://cloud.githubusercontent.com/assets/8203181/22386365/5701dff4-e49c-11e6-9f03-683a898a2d80.png)
![2m](https://cloud.githubusercontent.com/assets/8203181/22386368/586e65a6-e49c-11e6-9b8b-49ac4f11685f.png)
![3m](https://cloud.githubusercontent.com/assets/8203181/22386369/59f5dfda-e49c-11e6-8b61-7a305f0daeab.png)

**Comment by NicolasRannou** [comment]
Nice that looks really good! I think there might be no collisions between meshes in >90% of the cases but will be nice to handle it I agree.

Do the screenshots you sent also support semi-transparent objects?

**Comment by rwirz** [comment]
Yes, you only need to change the opacity of the backface mesh. For example, backface 0.5% opacity and frontface 0%. Frontface ever 0%!. I will start looking the contour thing

**Comment by rwirz** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8203181/22429711/1dec637e-e6d1-11e6-8381-6969772c1940.png)

**Comment by NicolasRannou** [comment]
That is so awesome! Can you share the latest version of you code somehow?  I'd like to update this lesson to show case the cutting as you did!

http://jsfiddle.net/gh/get/library/pure/fnndsc/ami/tree/master/lessons/02#run

Or just a PR if you can?

**Comment by rwirz** [comment]
http://jsfiddle.net/z66joa43/

Two things:
1. With VTK files I have not problems. With this STL, you can see a very thin line in some borders. The (frontface-backface) is not clean with this file.
2. I tried to align the clip plane with the slice, but I dont know what happened that I can not do it. I use this code (that works with my MRI). Also, the clip plane (x,0,0) is not parallel to the slice plane, so the slice plane is not parallel to some axis.:

stackHelper.index=120;
let nextWorldCoordinate = new THREE.Vector3(0, 0, stackHelper.index);
nextWorldCoordinate.applyMatrix4(stackHelper._stack.ijk2LPS);
let aux = -nextWorldCoordinate.x;
clipPlane.setComponents(1, 0, 0, aux);

**Comment by NicolasRannou** [comment]
http://jsfiddle.net/nicolasrannou/8mL1v35f/ ;) (quick and dirty but hey)

**Comment by NicolasRannou** [comment]
there is a z-fighting issue for the mesh, that is why you see the "noise".

**Comment by rwirz** [comment]
Great! Thanks!

**Comment by rwirz** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8203181/22474880/e54c5f9c-e7a2-11e6-8b3b-239c73350d0d.png)

I tested with 6 structures where all structures are in collision between them.
I set one structure per scene, so I have 6 "sceneClip". My 2d views are only renderered when there is a change in controls or stack.slice. Check the FPS.
Labels are perfect when structures are in different scene, in the same scene doesn;t work.

Thanks a lot.

**Comment by Bruit** [comment]
Hi @rwirz 
Your example look awesome, can you share your source code ? 
I want to do the exact same think except that I only want to render  the outline contour of the labels 

![contours](https://cloud.githubusercontent.com/assets/7459670/22552654/2118040a-e95a-11e6-91d6-fdb5ce88c6b9.jpg)

**Comment by NicolasRannou** [comment]
@Bruit I believe now we can not renderer "just the border", it has to be filled.

**Comment by NicolasRannou** [comment]
@rwirz, do you think it is possible to share the data from you first screenshots? (volume + mesh) or is it not public or patient related? Maybe we can use this data for a proper lesson/demo!

**Comment by rwirz** [comment]
Hi!

Last week I was on Holidays and I could not answer. This week, my boss is in the SPIE conference, so I can not answer yet, waiting news. But I will try to put it and, if not, explain it.

The web has different strategic from AMI helpers, the 3D scene contains all (meshes and three slices). The 2D views are only cameras which the layer activated. That means, for example, the axial view is a ortogonal camera looking at the axial slice that only see the axial slice (layers) and it is only rendered when the axial view is changed (mouse events mainly).

I am testing about borders. Scaling is not having good results, since a 3d scaling changes the shape of the mesh in the cut plane. A scaling in shaders maybe is better since is in 2D, something like (vertex+ normal*widthborder). I am testing!

**Comment by NicolasRannou** [comment]
Thanks for the update @rwirz !

I think I see what you mean -

About the borders, maybe the "easiest" approach is to work at the shaders level, wondering if we need 2 or 3 passes though, that might become to be way to much work on the shaders:
1- Draw the "filled" intersection to a texture.
2- Use the "filled" texture as a input in another shader and perform an edge detection somehow.
I am thinking using dfdx or fwidth to have a constant width line in pixel space.

I'll also probably give a shot to (2) as it *could* be quick to implement.

Just to be clear, that was the data I was talking about: I really like colors/shapes :)
https://cloud.githubusercontent.com/assets/8203181/22429711/1dec637e-e6d1-11e6-8381-6969772c1940.png

**Comment by NicolasRannou** [comment]
Closing for now -  we can re-open when going back to it.
See a quick demo: https://fnndsc.github.io/ami/#viewers_quadview

**Comment by NicolasRannou** [comment]
hey @rwirz - please let me ping you about that. In your application, did you end up rendering the "contours" on each animation frame or you only re-render when something has changed?
Thanks!

(FYI will push some stuff will "real" contours based on the current quadview soon!)

**Comment by rwirz** [comment]
Hi,

I don't have contours, I only have labels (and contours are...really... the minimum priority now, sorry)

In my application, the 2D views are only rendered when something happen. You should consider this, because FPS is improved a lot ( updating only one renderer and not 4 when the user is watching the 3D view).
If the control is not update, or the index or the labels, rendering the same is wasting of FPS.

I would like to see the contours, congrats! I saw you update some shader stuff with this.

Thanks

**Comment by rwirz** [comment]
Check a view:

https://mipresearch.org/examples/cochlear/ccwp/index.php

**Comment by eagle49** [comment]
this may not working when there are too much vertices on mesh.
