### ISSUE TITLE
Nifti Orientations issues

### ISSUE THREAD

**Issue by rwirz** [FNNDSC/ami#64]
Testing, sorry

**Comment by rwirz** [comment]
Ok, Now I am sure.

I have a mesh and a volume NRRD.

The mesh and the NRRD volume match perfectly.

However, if I use the same volume as NIFTI, the mesh and the nifti doesn't match. It is wrong the orientations. The head in NIFTI is inverted, upside down

**Comment by NicolasRannou** [comment]
Hi @rwirz,

Yes there is something going on with the orientation, I am not sure where the problem is yet...

**Comment by NicolasRannou** [comment]
Are your test datasets available somewhere? (nrrd, nifti and the mesh)

Can I re-open the issue or did you figure it out?

**Comment by rwirz** [comment]
Hi Nicolas,

I am using the MRI Head tumor volumes from 3D Slicer.

With NRRD is perfect as you see:
![nrrd_nifti](https://cloud.githubusercontent.com/assets/8203181/20486663/3809ee80-afc6-11e6-9b44-907c23fd3ed1.png)

However, with NIFTI is wrong:
![nifti_nrrd](https://cloud.githubusercontent.com/assets/8203181/20486684/599b56b0-afc6-11e6-9c3c-4b5e94a7924f.png)

And the volumes with the tumor segmentation:

https://drive.google.com/open?id=0B24ZHnv6xHO4YlRkc2JZU0xRaVE

**Comment by NicolasRannou** [comment]
Thanks for the pointer - do you have a link to the volume by any chance? I can not find it googling around.

**Comment by rwirz** [comment]
You can download from my google drive:

https://drive.google.com/open?id=0B24ZHnv6xHO4YlRkc2JZU0xRaVE

**Comment by NicolasRannou** [comment]
I got it figured out - I'll push a fix soon!

![screen shot 2016-11-22 at 1 29 18 pm](https://cloud.githubusercontent.com/assets/214063/20523908/b392046a-b0b7-11e6-95a6-73d71f1ad1d0.png)
