### ISSUE TITLE
Lesson to show how to create custom progress bar.

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ami#66]
Progress bar `A la XTK` would be cool.

**Comment by l0uch3** [comment]
Hi Nicolas,
I'm trying to create this feature.
I started by adding a "getProgress" function to both helpers.progressbar.js and loaders.base.js, they return the value of the progressbar progress in precentages.

However, a callback function would be more interesting, so I tried the following:
in helpers.progressbar.js
```
    setProgressCallback(funk) {
        this._callback = funk;
    }
```
and then 
```
if(progressBar.length > 0){
      progressBar[0].style.borderColor = color;
      progressBar[0].style.width = progress + '%';
      if (typeof this._callback === "function") {
          this._callback(progress);
      } else {
        console.log("Progressbar callback is not a function!");
      }
    }
```
(inside of the UpdateUI method.)
to access the callback setting function via the loader, I added the following to loaders.base.js
```
  setProgressCallback(funk) {
    this._progressBar.setProgressCallback(funk);
  }
```
I then add set the function of the callback before calling .free() on the loader
```
loader.setProgressCallback(function(progress){
            console.log("updating progressbar");
            $("#amiloadingbar").width(progress);
        });
```

However, the callback is not being recognized as a function. Is this a good approach or do you have other suggestions?
Do mind; I've never created callbacks before in javascript

**Comment by NicolasRannou** [comment]
See lesson 08: http://jsfiddle.net/gh/get/library/pure/fnndsc/ami/tree/master/lessons/08#run

It requires AMI 0.0.11+

**Comment by l0uch3** [comment]
Awesome! Thanks!
