### ISSUE TITLE
Feature to crop loaded DICOM data

### ISSUE THREAD

**Issue by l0uch3** [FNNDSC/ami#67]
I'm working with AMI to visualize DICOM data, a feature that would be cool to have is:

Cropping the DICOM data/stack by changing the dimensions and position of a hollow beam.

I'm pretty new to ThreeJS/AMI, but I'll try my best to add the functionality myself, any help is greatly appreciated.

**Comment by NicolasRannou** [comment]
Hi @l0uch3 -

Can you remind me which is the goal? To save the cropped data somehow or only for visualization?
Depending on the use case there are different possible solutions.

**Comment by l0uch3** [comment]
Hello @NicolasRannou 
The main goal is to show only the data inside the "selection beam" after cropping. Under the hood, the stack/frames itself don't have to be removed or anything. As long as clear coordinates of where the crop happened can be fetched. (the coordinates of the beam corners)

**Comment by l0uch3** [comment]
![image](https://cloud.githubusercontent.com/assets/9481598/20705276/9fe9cd2e-b622-11e6-9c4e-4042731f474d.png)
That's what I currently have; It's a selection beam that can be scaled and moved around, the next step is to perform the visual crop eg; hide the area around the selection.

**Comment by rwirz** [comment]
Hi,

I can suggest you two options:

1- Check https://github.com/daign/clipping-with-caps
     In this projects, you can move the walls of a box to select the beam boundaries and, using shaders, you       can clip it easily. This should be easy since you have all the code, you only need to remove the CAP thing.

2- Using clip planes in stack material. You dont need to learn shaders for this. You only need to define 6 planes than clip the stack

**Comment by NicolasRannou** [comment]
Yes probably doing that in the shaders is the easiest way.

There are a couple of things to be figured out but here would be the basic steps:
1- Pass `stack._lps2AABB` (aka `uWorldToAABB`) transform and the bounding box to use for cropping `uRoiAABBox` to the shaders.
2- In the shader, if `uWorldToAABB *vPos` not in `uRoiAABBox`, return. Else proceed.

I might not have time this week to work on that but basically you need to add stuff in:
1- uWorldToAABB and uRoiAABBox as uniforms in https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.data.uniform.js
2- Check if point is in ROI in the fragment shader:
https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.data.fragment.js#L60

Then we can generalize it for the other type of shaders.

Maybe we can also pass a flag to the shader to know if cropping is on/off. Or default cropping region could be the stack bounding box.

**AABB stands for Axe Aligned Bounding Box**

**Comment by l0uch3** [comment]
Thanks a lot for the info and help @NicolasRannou @rwirz ! 
I'm working on another part of the application at the moment, but will try to implement this as soon as I have time.

**Comment by NicolasRannou** [comment]
@l0uch3 can I also close this one?

**Comment by l0uch3** [comment]
@NicolasRannou Yup, this went together with the other issue you just closed 👍
