### ISSUE TITLE
Problem with orientations

### ISSUE THREAD

**Issue by rwirz** [FNNDSC/ami#68]
Hi,

I am checking the orientations and there is a problem when you are working with sagittal (PIL) orientation (with nii and nrrd, and checke with 3D Slicer)

For example,  if you have the volume in LPS, it works great. But , if the volume is PIL:
![bug_pil](https://cloud.githubusercontent.com/assets/8203181/20673297/2c743c2c-b54a-11e6-8431-ca21483ed7a7.png)

And there is something with the orto cameras. I have this view in LPS:

![bug_orto_lps](https://cloud.githubusercontent.com/assets/8203181/20673313/3df5cc68-b54a-11e6-88a2-29570e7ebfd4.png)

But with PIL is this view:
![bug_orto_pil](https://cloud.githubusercontent.com/assets/8203181/20673319/451b16c4-b54a-11e6-996f-b62077f76b2e.png)

I hope this help.

Volume in PIL and mesh for this case ( I changed the origin testing different things from previous model):

https://drive.google.com/open?id=0B24ZHnv6xHO4TDR4d3JIWlFTLWM

**Comment by NicolasRannou** [comment]
I introduced the bug while cleaning up - the volume loader was not handling the qfac properly - mesh and volume overlap as expected now.

**Comment by NicolasRannou** [comment]
(please open another issue is there is something that does not behave as you would expect it to with the orthographic camera)
