### ISSUE TITLE
volume rendering up to a certain slice

### ISSUE THREAD

**Issue by l0uch3** [FNNDSC/ami#69]
I was playing around with another cool feature, so I have the following slice view with the volume loader
![image](https://cloud.githubusercontent.com/assets/9481598/20759977/dcec12d4-b71e-11e6-81c5-e7520ede3c0b.png)
It would be very cool to be able to combine this with the volumerendering, so that the volumerender only shows up to the the slice indicated by the volume loader slice index (presumably the Yaxis, but any could be fine).
Since the volumerendering is quite heavy on the pc, this would reduce the load and also increase the usefulness, since it can be used to look "inside" certain parts of the scan.

Unfortunately, I'm not very exprienced with threejs/3D in general. But I have tried and look at the AMI code to see what might make this possible;
inside helpers.volumerendering.js the following code
```
this._uniforms.uDataDimensions.value = [this._stack.dimensionsIJK.x,
                                                this._stack.dimensionsIJK.y,
                                                this._stack.dimensionsIJK.z];
```
If instead of the true stack dimensions, this was passed the dimensions of the stack up to the slice, and was updated using the lut gui (or whatever other gui) whenever the slice index changed, would that show only the volumerender up to the slice index and not further?

**Comment by l0uch3** [comment]
I just tried my previously suggested approach with the following addition to the dat gui
```
var dimensionSlice = stackFolder.add(vrHelper.stack.dimensionsIJK, 'x', 0, stack.dimensionsIJK.x).step(1);
    dimensionSlice.onChange(function (value) {
        if (vrHelper.stack.dimensionsIJK) {
           vrHelper.stack.dimensionsIJK.x = value;
        }
    });
```
When testing the vrHelper.stack.dimensionsIJK.x value after changing the slider, it does return the new value, but the volumerender does not update. I'm going to try to expose the function/part of the helpers.volumerendering.js that is needed to recalculate the render and see if that works.

**Comment by NicolasRannou** [comment]
@l0uch3 try updating "vrHelper. uniforms.uWorldBBox.value = value;"

```
var dimensionSlice = stackFolder.add(vrHelper.stack.dimensionsIJK, 'x', 0, stack.dimensionsIJK.x).step(1);
    dimensionSlice.onChange(function (value) {
        if (vrHelper.stack.dimensionsIJK) {
           vrHelper.stack.dimensionsIJK.x = value;
           vrHelper. uniforms.uWorldBBox.value = vrHelper.stack.worldBoundingBox();
        }
    });
```

There may be a couple more things to be figured out but could already kind of work :)

**Comment by l0uch3** [comment]
@NicolasRannou Thanks for the quick feedback! Much appreciated!
I applied the change you suggested, and it does indeed work! Kind of :P 
![image](https://cloud.githubusercontent.com/assets/9481598/20762509/dc955d42-b726-11e6-9e23-65e44942f0ce.png)
As you can see, the problem I have now is that the render doesn't show much detail due to being overbright. I'm not sure if that's due to the scan data I'm using (I'm using [INCISIX From the osirix library](http://www.osirix-viewer.com/resources/dicom-image-library/) ) or because of some other setting that's not quite right.

Are settings like WW/WL WindowWidth/WindowCenter available for the volumerender? I'm guessing if those were applied to the volumerender in the same way they are applied to the slices, the information would be more clear.

**Comment by NicolasRannou** [comment]
Yes window width/level are available - https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.vr.uniform.js#L29-L34

It could also be related to the LUT that you are passing to the VR.helper.
See [opacity] in the VR example: https://fnndsc.github.io/ami/#vr_singlepass

Finally the VR shader will need extra work to support to nicely mix slices/meshes inside the visualization.

**Comment by jinchengxiaoge** [comment]
I 'like to do so a slice view with the volume loader .I don't know how to start ,how can I do it? Can this part of your code let me refer to it? thank you very much.

**Comment by l0uch3** [comment]
@jinchengxiaoge Yes, the code and references above + [ami lessons](https://github.com/FNNDSC/ami/#hello-ami) can help you to accomplish the result. Might need some fine tuning though.

**Comment by jinchengxiaoge** [comment]
Thank you very much.  I have saw the lessons.  I have not succeeded in debugging some of the code. Can you tell me which Part of the code that I should adjust? thank you again.

**Comment by NicolasRannou** [comment]
side note 1: to have the Volume rendering and slices overlay nicely it probably needs some extra passes in the shader.

side note 2: to make the Volume rendering less demanding in term of ressources, consider rendering the scene only when needed (see discussion https://github.com/FNNDSC/ami/pull/72)

**Comment by NicolasRannou** [comment]
@jinchengxiaoge what do you mean a slice view? in 2D or 3D? 1 slice, N slices? Volume rendering or not?

**Comment by jinchengxiaoge** [comment]
I mean that i'd like to do this
![1](https://cloud.githubusercontent.com/assets/24455151/21215463/5b17b352-c2dc-11e6-8df6-13bcea3e8b72.png)
I don't know hoe to do

**Comment by NicolasRannou** [comment]
@jinchengxiaoge sure, that is pretty straight forward - can you open an new issue and detail the problem and what you do not know how to do? so we can continue the discussion there?

**Comment by jinchengxiaoge** [comment]
ok,

**Comment by NicolasRannou** [comment]
@l0uch3 closing - please re-open if you couldn't get working what you were looking for!
