### ISSUE TITLE
Plane Orientation

### ISSUE THREAD

**Issue by rwirz** [FNNDSC/ami#73]
Hi,

I think there is some bug with plane orientation. Check this example:
http://jsfiddle.net/np9g01n1/

The plane should be in the same orientation than the blue line, right?

**Comment by NicolasRannou** [comment]
The following works:
http://jsfiddle.net/nicolasrannou/np9g01n1/1/

StackHelper uses local space (IJK) and not world space (LPS) as a reference space so we need to play around with some maths to get it to work properly.

Please re-open if not fixed -

**Comment by rwirz** [comment]
Thanks for the information :)
