### ISSUE TITLE
How to draw to  a certain slice?

### ISSUE THREAD

**Issue by jinchengxiaoge** [FNNDSC/ami#78]
I want to achieve this effect, how should I do? 
![qq 20161215160408](https://cloud.githubusercontent.com/assets/24455151/21216153/29d775d0-c2e0-11e6-99c6-6b08e4ea3e03.png)

**Comment by NicolasRannou** [comment]
is it what you are looking for: https://fnndsc.github.io/ami/#viewers_quadview ?

See the top/left renderer, you might have to cherry pick the code you are interested in from https://github.com/FNNDSC/ami/blob/master/examples/viewers_quadview/viewers_quadview.js

**Comment by l0uch3** [comment]
@NicolasRannou does the quadview have the black treshold filtering like in his example? Seems in his screenshot the black/dark areas are filtered out. It's the kind of tresholding that XTK does in (Silice:Drop)[http://slicedrop.com] for DICOM imaging.

**Comment by NicolasRannou** [comment]
AMI doesn't have it yet but it is very easy to add if useful.

**Comment by NicolasRannou** [comment]
Closing in favor of #80 - please re-open if needed
