### ISSUE TITLE
Negative values not properly handled

### ISSUE THREAD

**Issue by YiiGuxing** [FNNDSC/ami#79]
![20161220-121556](https://cloud.githubusercontent.com/assets/10737066/21338117/32d842be-c6ae-11e6-834f-2cf222157208.png)

**Comment by NicolasRannou** [comment]
Hi @YiiGuxing , can you share the dataset with us somehow?

Does it look as epected if you upload it in https://fnndsc.github.io/ami/#viewers_upload

**Comment by NicolasRannou** [comment]
It looks like the intensities are inverted - did you set the `stackHelper.slice.invert = true;` somehow? It looks like the colors are inverted.

**Comment by YiiGuxing** [comment]
![20161229-100535](https://cloud.githubusercontent.com/assets/10737066/21535546/8765df76-cdb1-11e6-8f69-77fa31610436.png)
[01_1.2.392.200036.9116.2.5.1.3268.2047634594.1465786714.389157.dcm.zip](https://github.com/FNNDSC/ami/files/676503/01_1.2.392.200036.9116.2.5.1.3268.2047634594.1465786714.389157.dcm.zip)

**Comment by NicolasRannou** [comment]
Bug confirmed - renaming

**Comment by NicolasRannou** [comment]
I figured out the solution, got to test it a bit more then will push the fix!
Thanks for reporting the bug again!

<img width="758" alt="screen shot 2016-12-29 at 11 47 09 am" src="https://cloud.githubusercontent.com/assets/214063/21542224/a8f765be-cdbc-11e6-8f49-ca32981d5e1c.png">

**Comment by NicolasRannou** [comment]
ami 0.0.13+ should be working as expected!

![screen shot 2016-12-30 at 3 51 06 pm](https://cloud.githubusercontent.com/assets/214063/21566908/fdbc74a4-cea7-11e6-96f1-ce2bf77378cc.png)

Please re-open if issue persists.

**Comment by NicolasRannou** [comment]
Live demo at: https://fnndsc.github.io/ami/#viewers_upload
