### ISSUE TITLE
[feature] Add threshold property to the shaders

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ami#80]
In order to achieve something like:

![qq 20161215160408](https://cloud.githubusercontent.com/assets/24455151/21216153/29d775d0-c2e0-11e6-99c6-6b08e4ea3e03.png)

**Comment by PauloCarvalhoRJ** [comment]
Hello!  Do you mean not rendering certain cells?  If you use VTK for visualization, you can use the `vtkThreshold` class to not render cells:
https://github.com/PauloCarvalhoRJ/gammaray/commit/253c66df360d07348824d3fc0554278a0d9fa58d?diff=unified
In my case I used a second array of 0s and 1s for thresholding, but you can use the values in your own data array.

**Comment by NicolasRannou** [comment]
Hi @PauloCarvalhoRJ , the idea for now was to render only voxel within a certain range and make the voxels out of the range transparent:

```
threshold min: 49
threshold max: 120

voxel intensity: 50 -> display
voxel intensity: 3 -> transparent
```

Using an extra array for masking sounds fine but may not work in our case as it is too much data being passed to the GPU -

**Comment by PauloCarvalhoRJ** [comment]
Hi, Nicolas, VTK is pretty smart.  Rest assure an array of on/off flags has low footprint.  I work with seismic cube visualization which are similarly sized problem.  Anyway, if you want to avoid another data cube, you can assign transparency levels via color table (alpha channel).  Do you know how?

**Comment by NicolasRannou** [comment]
@PauloCarvalhoRJ I believe you may be able to use segmentationLUTs: see https://github.com/FNNDSC/ami/pull/176

1- Create the lookup table you want, such as: https://github.com/FNNDSC/ami/blob/dev/src/presets/presets.segmentation.freesurfer.js
2- Create a segmentation lut and provide data from 1) in the constructor (https://github.com/FNNDSC/ami/blob/dev/src/helpers/helpers.segmentationlut.js)
3- pass data to the shaders:
```
uniform.uLutSegmentation.value = 1; // activate lut
uniform.uTextureLUTSegmentation.value = segmentationLut.texture;
```
https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.data.uniform.js#L71-L80

**Comment by PauloCarvalhoRJ** [comment]
That's it: color table, or LUT in VTK jargon.
