### ISSUE TITLE
jittery coronal and sagittal views

### ISSUE THREAD

**Issue by SevenSinS02** [FNNDSC/ami#84]
While viewing the lessons and examples, when viewing sagittal or coronal there are these noise or static that appear close to the bounding box. What exactly causes this?
![snip20170117_1](https://cloud.githubusercontent.com/assets/14374646/22022971/438b0e46-dcea-11e6-8677-cadc988f0082.png)

**Comment by NicolasRannou** [comment]
Thanks for reporting!
That is the bug in the interpolation process.
In the shaders, we access voxel with negative indices during interpolation and as a result get those artifacts.
Will look into it ASAP

**Comment by NicolasRannou** [comment]
I found a fix - will test it a bit more and push it:
```
// in shaders.interpolatiion.trilinear
vec3 lower_bound = vec3(floor(currentVoxel.x), floor(currentVoxel.y), floor(currentVoxel.z));
if(lower_bound.x < 0.){
  lower_bound.x = 0.;
}
if(lower_bound.y < 0.){
  lower_bound.y = 0.;
}
if(lower_bound.z < 0.){
  lower_bound.z = 0.;
}
```

**Comment by NicolasRannou** [comment]
![screen shot 2017-01-17 at 6 35 53 pm](https://cloud.githubusercontent.com/assets/214063/22032239/d4c01cc8-dce3-11e6-8c0f-92292c49da8e.png)

**Comment by NicolasRannou** [comment]
The updated example is now live at: https://fnndsc.github.io/ami/#xtk_lesson13

Please re-open if something still doesn't look right!

**Comment by SevenSinS02** [comment]
It works just lovely! No need to reopen it. Thanks a bunch, Nicolas.

**Comment by NicolasRannou** [comment]
You're welcome @SevenSinS02 ! Do not hesitate to open issue if something looks wrong or if you are looking for specific features!
