### ISSUE TITLE
Loader should throw progress events and do not include progress helper

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ami#87]
Loader should throw progress events so we can move progress helper out of it.

**Comment by chenkaiC4** [comment]
@NicolasRannou 

let Lorder and progress bar both extend by Emitter, and Lorder send the event:


```
// event: event:loader:loading`
{
   type: 'loading',
   total: 100,
   loaded: 23,
}
```

```js
// event: event:loader:parsing`
{
   type: 'parsing',
   // need discussion the data content here
}
```

**Comment by chenkaiC4** [comment]
@NicolasRannou Please assign this issue to me, i'd like have a try 🎉

**Comment by NicolasRannou** [comment]
In our case, loading the data means "fetching + parsing" the data.
It could be nice if we send the status of the current file and also the overall status of the loader.

For instance, if I load 8 files, what about something like:
```
// 'fetch' event
{
   type: 'fetch',
   total: 100,       // filename.dcm has 100 in total
   progress: 23, // fetched 23 from filename.dcm
   totalFetched: 8, // we have 8 files to fetch in total
   progressFetched: 3, // we fetched 3 files so far
   target: 'filename.dcm'
   // could contain more detail info about the fetching somehow
}
```

```
// 'parse' event
{
   type: 'parse',
   total: 100,  // got 100 to parse in this file
   progress: 23, // parsed 23 of this file
   totalParsed: 8, // we have 8 files to parse
   progressParsed: 3, // 3 files have been parsed so far
   target: 'filename.dcm'
  // could contain more detail info about the parsing somehow
}
```

```
// parse error
{
   type: 'error',
   status: 'error message?'
   data: {} // some data if needed? cold contain the status.
}
```

```
// load event
{
   type: 'load',
   status: 'sucess message?'
   data: {} // some data if needed? could contain the status.
}
```

also message like: before-fetch, after-fetch, before-parse, after-parse, before-load, after-load would be useful...

**Comment by chenkaiC4** [comment]
yes, the event hooks your proposed is very good. But, as i don't have enough knowledge of medical imaging process, though i have read the source code of Loaders and Parsers, some keywords your written confused me. need some explanation. @NicolasRannou 

1.
> For instance, if I load 8 files

is the 8 files means the arguments of function [load](https://github.com/FNNDSC/ami/blob/dev/src/loaders/loaders.base.js#L150) ?

2. 

```
// 'fetch' event
{
   type: 'fetch',
   total: 100,       // filename.dcm has 100 in total
   progress: 23, // fetched 23 from filename.dcm
   totalFetched: 8, // we have 8 files to fetch in total
   progressFetched: 3, // we fetched 3 files so far
   target: 'filename.dcm'
   // could contain more detail info about the fetching somehow
}
```

what `filename.dcm` have amount to 100 ?

3. 

> also message like: before-fetch, after-fetch, before-parse, after-parse, before-load, after-load would be useful...

some mapping logic need confirm 😄 

- `fetch` --> [fetch](https://github.com/FNNDSC/ami/blob/dev/src/loaders/loaders.base.js#L70)
- `parse`  --> [parse](https://github.com/FNNDSC/ami/blob/dev/src/loaders/loaders.base.js#L133)
- `load`  --> [load](https://github.com/FNNDSC/ami/blob/dev/src/loaders/loaders.base.js#L150)

-----
from the source code, i have inferred that: we can load more than one resources once(e.x. dicom file), and every resource with url supplied will be fetch, then be parsed. so what the `filename.dcm has 100 in total` mean ?

**Comment by chenkaiC4** [comment]
another two question 😄 

1. 
[promise.all](https://github.com/FNNDSC/ami/blob/dev/src/loaders/loaders.base.js#L163)

what i have know about `promise.all` is that if any promise raise a rejection, the `promise.all` will reject。this is why you use [this._data.push(data)](https://github.com/FNNDSC/ami/blob/dev/src/loaders/loaders.base.js#L136); to process the data to avoid the case above ? and get data as follow:

``` js
loader.load(files)
.then(function(__data__) {
    // use loader.data[0] instead of __data__ to avoid promise.all crash
    var series = loader.data[0].mergeSeries(loader.data);
    var stack = series[0].stack[0];
```

2. the fetch process include the parse process. how about decouple the two logic ?

**Comment by NicolasRannou** [comment]
:)

1. yes loading 8 files with the load function.
2. 100 was just an example, it is the "total" returned by the XMLHTTPRequest - https://github.com/FNNDSC/ami/blob/dev/src/loaders/loaders.base.js#L80
3. yes.
4. (1 bis) yes but might be better to handled rejection properly - not sure which is the best way
5.   where? I'm all in for decoupling things!

Thanks!

**Comment by chenkaiC4** [comment]
@NicolasRannou thanks！I have got enough information for refactor, let me have a try. i will consult you when need. ☀️

**Comment by NicolasRannou** [comment]
Awesome!

For now I would just leave the Progress helper for backward compatibility, but also add a console.warning each time we call it to let users know this approach is deprecated and will stop working in the near future!

**Comment by NicolasRannou** [comment]
Thanks again @chenkaiC4 !
