### ISSUE TITLE
Data to world coordinates

### ISSUE THREAD

**Issue by SevenSinS02** [FNNDSC/ami#91]
Hi @NicolasRannou, once again,

How would I be able to convert from data to world coordinates. Basically, I want to dynamically create  meshes from the data coordinates. However, I'm missing the world coordinates for the Voxel helper class.
Please note that  I only have the data coordinates.

**Comment by NicolasRannou** [comment]
@SevenSinS02 - you will need the stack object (or stack Helper, that contains the stack object):
```
// i, j and k are the data coordinates
let worldCoordinate = new THREE.Vector3(i, j, k).applyMatrix4(stack._ijk2LPS);
```
