### ISSUE TITLE
Ruler widget

### ISSUE THREAD

**Issue by SevenSinS02** [FNNDSC/ami#93]
Hi @NicolasRannou ,

I'm having trouble hiding the  ruler widget. I've tried manually setting widget._meshDisplayed,widget._mesh.visible,widget._displayed to false. Even the properties of individual handle objects in widget._handles[] to false. But to no avail. Am I doing something wrong?

**Comment by NicolasRannou** [comment]
Yes I'm afraid there is no API for that yet -
You need to manually hide:
Ruler:
```
// DOM element
_line.style.display = 'none';
_distance.style.display = 'none';
// THREEJS mesh
_mesh.visible = false;
```
Handles:
```
// DOM element
_dom.style.display = 'none';
// THREEJS mesh
_mesh.visible = false;
```

**Comment by SevenSinS02** [comment]
Thanks @NicolasRannou! Worked like a charm.
