### ISSUE TITLE
Fetching a DICOM using an URL throws "unsupported extenson: "

### ISSUE THREAD

**Issue by sherylj** [FNNDSC/ami#94]
In my case, the DICOM URLs contain the UID (For e.g: 1.2.826.0.1.36323043.8.620.343473176743640683421634137892154), so in the class LoadersVolumes, the data.extension splits the filename incorrectly and gives a wrong extension leading to the above error.

The workaround I did was to check the extension length and then select the ParsersDicom as the parser. This works for me but there might be a better was to select the right parser.

```
// to avoid assuming all extensions are file format : ePAD case
                  if (data.extension.length <= 10) {
                    parser = this._parser(data.extension);
                    if (!parser) {
                      reject(data.filename + ' can not be parsed.');
                    }
                  } else {
                    parser = ParsersDicom;
                  }
```

**Comment by NicolasRannou** [comment]
Thanks for lettting us know will look into that!

**Comment by NicolasRannou** [comment]
Hmm I can not reproduce that... I renamed a DICOM file "1.2.826.0.1.36323043.8.620.343473176743640683421634137892154" and it loads properly.

Which is the exact URL you are passing to the loader?

**Comment by sherylj** [comment]
It's actually a WADO call. An example WADO URL (taken from [here](http://chafey.blogspot.com/2014/09/dicom-wado-and-wado-uri.html)) would be :
```
http://localhost:8080/wado?requestType=WADO&studyUID=1.3.6.1.4.1.25403.166563008443.5076.20120418075541.1&seriesUID=1.3.6.1.4.1.25403.166563008443.5076.20120418075541.2&objectUID=1.3.6.1.4.1.25403.166563008443.5076.20120418075557.1&contentType=application%2Fdicom
```

In my example, it's the similar URL but I could set studyUID=* and seriesUID=* and just give the objectUID=1.2.826.0.1.36323043.8.620.343473176743640683421634137892154

It's able to load the the URL but not parsing it correctly. The error looks like 

```
unsupported extension: 343473176743640683421634137892154&contentType=application%2Fdicom
ami.min.js:20 TypeError: parser is not a constructor
    at ami.min.js:20
    at ami.min.js:20
ami.min.js:20 oops... something went wrong...
ami.min.js:20 ?requestType=WADO&studyUID=*&seriesUID=*&objectUID=1.2.826.0.1.36323043.8.620.343473176743640683421634137892154&contentType=application%2Fdicom can not be parsed.
ami.min.js:20 
```

**Comment by NicolasRannou** [comment]
Thanks for the details - 

To immediately bypass the issue, just add `&amihack=filename.dcm` at the end of the WADO url.
I'll fix it in the loader by actually properly parsing the url (path + query) rather than just expecting the url to be a filename.

**Comment by sherylj** [comment]
Sure, I will add that extension to the WADO call to workaround this issue.
