### ISSUE TITLE
Getting relative position of cube inside StackHelper

### ISSUE THREAD

**Issue by l0uch3** [FNNDSC/ami#95]
![image](https://cloud.githubusercontent.com/assets/9481598/22396986/884845e2-e566-11e6-8606-ac7a913f4c86.png)
I have the setup as depicted in the screenshot. The light blue cube is draggable.
The cube is a normal ThreeJS THREE.Mesh and a child object of the StackHelper in the scene.
I'm looking for a way to find the coordinates of the vertices of the light blue box, relative to its parent (StackHelper).
But not with the center of the StackHelper being 0,0,0, rather, one of the vertices should be the origin.

![example](https://cloud.githubusercontent.com/assets/9481598/22397035/50b7a1ca-e568-11e6-949d-c5ad451ba4ef.png)
The example shows what I'm trying to achieve in 2D, the red square is the StackHelper (containing the dicom slices/stack) and the light blue square its child.

I noticed that the geometry object of the THREE.Mesh contains vertices, but their numbers seem completely wrong.

**Comment by NicolasRannou** [comment]
What are you trying to achieve in this example?

**Comment by l0uch3** [comment]
I'm trying to get the coordinates of the vertices of the light blue area inside of the stackhelper, in order to represent a portion of the dicom scan and not the entire scan. (Basically, cropping :) )
(So with the stackhelper as range). Not the "true" ThreeJS coordinates, but the coordinates of the stack basically, so if for example the stack IJK is (512,512,165) I should get 8 points within that range, representing the light blue cube.

**Comment by NicolasRannou** [comment]
Sounds good! And inside the slight bue box, you want to see the slice or to do some volume rendering?

**Comment by l0uch3** [comment]
Doing volume rendering in the light blue selection cube would be cool, but I really just need the coordinates for the back-end processing that happens with the dicom files. 
Currently I do it this way:

`var boxGeometry = new THREE.BoxGeometry(
                    helper.stack.dimensionsIJK.x,
                    helper.stack.dimensionsIJK.y,
                    helper.stack.dimensionsIJK.z
                    );
            // we use this offsect to center the first voxel on (0, 0, 0)
            // in IJK space (is it correct?)
            var offset = new THREE.Vector3(-0.5, -0.5, -0.5);
            // box is centered on 0,0,0
            // we want first voxel of the box to be centered on 0,0,0
            // in IJK space
            boxGeometry.applyMatrix(new THREE.Matrix4().makeTranslation(
                    helper.stack.halfDimensionsIJK.x + offset.x,
                    helper.stack.halfDimensionsIJK.y + offset.y,
                    helper.stack.halfDimensionsIJK.z + offset.z)
                    );
            var boxMaterial = new THREE.MeshBasicMaterial({
                wireframe: true,
                color: 0x00FF00
            });
            var helperCube = new THREE.Mesh(boxGeometry, boxMaterial);
            helperCube.applyMatrix(helper.stack.ijk2LPS);
            stackHelper.add(helperCube);
            helperCube.add(selectionCube);`

With TransformControls added onto the selectionCube for easy positioning etc.

Then I get the coordinates like so (this could be more simple for sure):

`var truePosX = selectionCube.position.x + ((selectionCube.geometry.parameters.width * selectionCube.scale.x) / 2);
    var truePosY = selectionCube.position.y + ((selectionCube.geometry.parameters.height * selectionCube.scale.y) / 2);
    var truePosZ = selectionCube.position.z + ((selectionCube.geometry.parameters.depth * selectionCube.scale.z) / 2);
    var width = selectionCube.geometry.parameters.width * selectionCube.scale.x;
    var height = selectionCube.geometry.parameters.height * selectionCube.scale.y; //z
    var depth = selectionCube.geometry.parameters.depth * selectionCube.scale.z; //y
    var halfWidth = width / 2;
    var halfHeight = height / 2;
    var halfDepth = depth / 2;

	// upper region
    // q -- q0
    // |    |
    // q -- q

	// lower region
    // q -- q
    // |    |
    // q7-- q

    var q0 = new THREE.Vector3(truePosX, truePosY, truePosZ);
    var q1 = new THREE.Vector3(truePosX, truePosY, truePosZ - depth);
    var q2 = new THREE.Vector3(truePosX, truePosY - height, truePosZ);
    var q3 = new THREE.Vector3(truePosX, truePosY - height, truePosZ - depth);
    var q4 = new THREE.Vector3(truePosX - width, truePosY, truePosZ);
    var q5 = new THREE.Vector3(truePosX - width, truePosY, truePosZ - depth);
    var q6 = new THREE.Vector3(truePosX - width, truePosY - height, truePosZ);
    var q7 = new THREE.Vector3(truePosX - width, truePosY - height, truePosZ - depth);`

I just quickly edited that for readability, so some mistakes might have been made

**Comment by NicolasRannou** [comment]
That looks very complicated - can you just get the World Coordinates of the corners of the Box then trasnform it to IJK using the `stack._lps2IJK` transform? Such as in:
```
  static worldToData(stack, worldCoordinates) {
    let dataCoordinate = new THREE.Vector3()
      .copy(worldCoordinates)
      .applyMatrix4(stack._lps2IJK);

    // same rounding in the shaders
    dataCoordinate.addScalar(0.5).floor();

    return dataCoordinate;
```

**Comment by l0uch3** [comment]
Awesome! I knew there had to be an easier way, thank you!
Is there a nice function to clamp the coordinates within the range of the IJK?

**Comment by l0uch3** [comment]
Yeah so when you pass that function worldCoordinates that lie outside of the IJK, it throws an error. The coordinates should be clamped to be within the IJK range

**Comment by NicolasRannou** [comment]
Where does it throw an error? In your app?

Just applying `stack.lps2IJK` transform should always work...

Then you can clamp the returned IJK value by comparing against stack.dimensionsIJK.

Something like:
```
if(value.x < 0) value.x = 0;
if(value.y < 0) value.y = 0;
if(value.z < 0) value.z = 0;
if(value.x > stack.dimensionsIJK.x) value.x =  stack.dimensionsIJK.x;
if(value.y > stack.dimensionsIJK.y) value.y =  stack.dimensionsIJK.y;
if(value.z > stack.dimensionsIJK.z) value.z =  stack.dimensionsIJK.z;
```

**Comment by NicolasRannou** [comment]
Can I close it or do you still have an issue @l0uch3 ?

**Comment by l0uch3** [comment]
I'm very sorry! I forgot to inform you that I successfully got the data I wanted, thanks for your help!

**Comment by NicolasRannou** [comment]
Awesome!
