### ISSUE TITLE
Intersection between an arbitrary plane and a slice

### ISSUE THREAD

**Issue by SevenSinS02** [FNNDSC/ami#99]
Hi @NicolasRannou ,

I'm picking three points on three different slices on the axial plane to  get a plane(triangle). I'm interested in finding out the points of intersection that each slice has with this plane.
Should I cast a ray from one vertex of the triangle towards other the other two vertices? Or is there a better way? Perhaps the coreIntersections.aabbPlane method?

**Comment by SevenSinS02** [comment]
Okay. So I've tried taking each slice as the aabb parameter and the new formed plane as the plane parameter. The question now is how do i calculate the new plane position and direction ?

**Comment by SevenSinS02** [comment]
Never mind, I've solved it by ray casting from 1 vertex to the other two vertices. 
However, is there a better way to do the same?

**Comment by NicolasRannou** [comment]
Hi @SevenSinS02 , can you tell more about what you are trying to achieve or send a screenshot?

Thanks!

**Comment by SevenSinS02** [comment]
Hi @NicolasRannou ,

I'm trying to find the intersection points between the triangle and each axial slice.

![snip20170210_2](https://cloud.githubusercontent.com/assets/14374646/22816072/b36c966e-ef85-11e6-813f-0952f317f038.png)
![snip20170210_1](https://cloud.githubusercontent.com/assets/14374646/22816079/b8b0f980-ef85-11e6-90af-dc90c1dff4ba.png)

**Comment by NicolasRannou** [comment]
Hi @SevenSinS02 , do you just want to "draw" the intersection between the triangle and the slices? Between the plane represented by the triangle and the slices? Or do you want to get the exact coordinates of the intersection points for a specific usage?

**Comment by SevenSinS02** [comment]
Hi @NicolasRannou , I would just like the coordinates of the intersection points. Oh and I forgot to mention, that triangle is an imaginary one. I basically have three points which form the vertices of the triangle. That forms a triangle similarly to the one above and from that, get the intersection points with each axial slice.

**Comment by NicolasRannou** [comment]
https://github.com/FNNDSC/ami/blob/dev/src/core/core.intersections.js#L255 may help in your case but you will have to do some extra stuff to make sure the intersection is in the segment.


But yes basically "raycasting" from one vertex to another is the way to go - you got it working right?

**Comment by SevenSinS02** [comment]
Ah Yes. I see. I have got it working. However, I'm not sure if it's exactly right. Could you tell me if the  snippet below is the right way? 

//plane
let position= this._stackHelper.slice.planePosition;
let direction= this._stackHelper.slice.planeDirection;
let plane= {
        position,
        direction
      };

//ray
 let raycaster= new THREE.Raycaster();
let rayDirection= this._voxels[1].voxel.worldCoordinates.sub(this._voxels[0].voxel.worldCoordinates).
normalize();

raycaster.ray.origin= this._voxels[0].voxel.worldCoordinates;
raycaster.ray.position= raycaster.ray.origin;
raycaster.ray.direction= rayDirection;

let intersectionPoint= coreIntersections.rayPlane(raycaster.ray, plane);

**Comment by NicolasRannou** [comment]
One issue I see there is the the plane info is in "data coordinate system" and the ray info is on "world coordinate system"

**Comment by SevenSinS02** [comment]
Ahh yes. My mistake. That was indeed supposed to be   _voxel.dataCoordinates_. 
I guess it's all good then. Thanks a bunch!
